### ISSUE TITLE
Failed resolution of: Ljavax/management/NotificationListener;

### ISSUE THREAD

**Issue by iman2420** [sedmelluq/lavaplayer#109]
Hope someone can help me. I am having this error when running my app:

      `    04-18 02:33:00.765 9541-9541/ E/AndroidRuntime: FATAL EXCEPTION: main
        Process: , PID: 9541
        java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/management/NotificationListener;
        at chatkit.sample.features.demo.custom.media.CustomMediaMessagesActivity.onCreate(CustomMediaMessagesActivity.java:189)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
        Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.management.NotificationListener" on path: DexPathList[[zip file "/data/app/-2/base.apk", zip file "/data/app/-2/split_lib_dependencies_apk.apk", zip file "/data/app/-2/split_lib_slice_0_apk.apk", zip file "/data/app/-2/split_lib_slice_1_apk.apk", zip file "/data/app/-2/split_lib_slice_2_apk.apk", zip file "/data/app/-2/split_lib_slice_3_apk.apk", zip file "/data/app/-2/split_lib_slice_4_apk.apk", zip file "/data/app/-2/split_lib_slice_5_apk.apk", zip file "/data/app/-2/split_lib_slice_6_apk.apk", zip file "/data/app/-2/split_lib_slice_7_apk.apk", zip file "/data/app/-2/split_lib_slice_8_apk.apk", zip file "/data/app/-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/-2/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at chatkit.sample.features.demo.custom.media.CustomMediaMessagesActivity.onCreate(CustomMediaMessagesActivity.java:189) 
        at android.app.Activity.performCreate(Activity.java:6662) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

My gradle dependencies below:

    `      
      apply plugin: 'com.android.application'
      apply plugin: 'com.jakewharton.butterknife'
      
      repositories {
          google()
          jcenter()
          mavenCentral()
          maven { url 'https://maven.fabric.io/public' }
      }
      android {
          compileSdkVersion 27
          defaultConfig {
              multiDexEnabled true
      
              vectorDrawables.useSupportLibrary = true
              applicationId "com.android.xxx"
              minSdkVersion 16
              targetSdkVersion 27
              buildToolsVersion '28.0.0-rc1'
              versionCode 1
              versionName "1.0"
              testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
          }
          buildTypes {
              release {
                  minifyEnabled false
                  proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
              }
          }
          compileOptions {
              targetCompatibility JavaVersion.VERSION_1_8
              sourceCompatibility JavaVersion.VERSION_1_8
          }
      
          packagingOptions {
              pickFirst 'META-INF/license.txt'
              exclude 'META-INF/DEPENDENCIES.txt'
              exclude 'META-INF/LICENSE.txt'
              exclude 'META-INF/NOTICE.txt'
              exclude 'META-INF/NOTICE'
              exclude 'META-INF/LICENSE'
              exclude 'META-INF/DEPENDENCIES'
              exclude 'META-INF/notice.txt'
              exclude 'META-INF/license.txt'
              exclude 'META-INF/dependencies.txt'
              exclude 'META-INF/LGPL2.1'
              exclude 'META-INF/rxjava.properties'
              exclude 'org/apache/*' // for duplicate use in chatKit
              exclude 'org/apache/http/version.properties'
              exclude 'org/apache/http/client/version.properties'
              exclude 'org/apache/http/entity/mime/version.properties'
              exclude 'org/apache/http/auth/AuthSchemeFactory/version.properties'
          }
      
          afterEvaluate {
              tasks.matching {
                  it.name.startsWith('dex')
              }.each { dx ->
                  if (dx.additionalParameters == null) {
                      dx.additionalParameters = ['--multi-dex']
                  } else {
                      dx.additionalParameters += '--multi-dex'
                  }
              }
          }
          dexOptions {
              preDexLibraries = false
              javaMaxHeapSize "2g" // 2g should be also OK
          }
      }
      ext {
          supportVersion = '27.0.3'
          picassoVersion = '2.5.2'
          circleImageViewVersion = '2.1.0'
          shapeImageViewVersion = '0.9.3'
          circleindicatorVersion = '1.2.2@aar'
          uploadServiceVersion = "3.4.2"
      
      }
      dependencies {
          implementation fileTree(include: ['*.jar'], dir: 'libs')
      
          // Butter Knife
          implementation 'com.jakewharton:butterknife:8.8.1'
          annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
          implementation 'com.android.support:multidex:1.0.1'
      
          // MaterialTextField
          implementation 'com.github.florent37:materialtextfield:1.0.7'
      
          // Network monitoring
          implementation 'com.novoda:merlin:1.1.6'
      
          // Volley http library
          implementation 'com.android.volley:volley:1.0.0'
      
          // Pretty Toast
          implementation 'ua.com.crosp.solutions.library:pretty-toast:0.2.0'
      
          // PageIndicatorView
          implementation 'com.romandanylyk:pageindicatorview:1.0.0'
      
          // Material About
          implementation 'com.github.jrvansuita:MaterialAbout:0.2.0'
      
          // rebound
          implementation 'com.facebook.rebound:rebound:0.3.8'
      
          // CircleImageView
          implementation 'de.hdodenhof:circleimageview:2.2.0'
      
          // Customizable Timeline View for Android
          implementation 'com.github.qapqap:TimelineView:v1.6'
      
          // Android Chart
          implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
      
          // implementation 'com.github.stfalcon:chatkit:0.2.2'
          implementation "com.github.siyamed:android-shape-imageview:$shapeImageViewVersion"
      
          // Utils
          implementation "me.relex:circleindicator:$circleindicatorVersion"
          //Android Upload Service
          implementation "net.gotev:uploadservice-okhttp:$uploadServiceVersion"
          implementation "net.gotev:uploadservice:$uploadServiceVersion"
      
          // Android View Animations
          implementation 'com.daimajia.easing:library:2.0@aar'
          implementation 'com.daimajia.androidanimations:library:2.3@aar'
      
          // Java WebSockets
          implementation('io.socket:socket.io-client:0.8.3') {
              exclude group: 'org.json', module: 'json'
          }
      
          // Android library project for cropping images
          implementation 'com.soundcloud.android:android-crop:1.0.1@aar'
          implementation('com.crashlytics.sdk.android:answers:1.4.1@aar') {
              transitive = true
          }
          implementation project(':chatkit')
          //noinspection GradleDependency
          implementation 'com.android.support:support-vector-drawable:27.1.0'
          //noinspection GradleDependency
          implementation 'com.android.support:design:27.1.0'
          //noinspection GradleDependency
          implementation 'com.android.support:support-v4:27.1.0'
          //noinspection GradleDependency
          implementation 'com.android.support:appcompat-v7:27.1.0'
          // CircularProgressBar
          implementation 'com.mikhaellopez:circularprogressbar:1.1.1'
          //Gilde
          implementation 'com.github.bumptech.glide:annotations:4.7.1'
          annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
          // Runtime Permission
          implementation 'com.github.florent37:runtime-permission:1.0.1'
          // Audio player library for Discord
          implementation ('com.sedmelluq:lavaplayer:1.2.63'){
              transitive = true;
          }
      
      }
      `
And error on this line in activity:

            ` DefaultAudioPlayerManager playerManager = new DefaultAudioPlayerManager();
             AudioSourceManagers.registerRemoteSources(playerManager);
             AudioPlayer audioPlayer = playerManager.createPlayer();`

**Comment by sedmelluq** [comment]
It is not designed to work with Android.
