### ISSUE TITLE
YouTube Streams occasionally stop with TrackEndEvent, despite still running on the YT

### ISSUE THREAD

**Issue by MCOfficer** [sedmelluq/lavaplayer#112]
I've brought this up on discord before, but i wanted to make sure it's "conserved" here in case anyone has the same problem.

I run a Bot that is supposed to play livestreams 24/7. Every few hours, a TrackEndEvent will happen, despite the actual stream on YouTube still being up & running. 

This seems to be independant of the stream, or the machine i host on. I couldn't find anything unusual (like a short loss of connection) in the logs either. The only thing all these streams have in common is being hosted on YouTube. The Audiobuffer size doesn't seem to affect the frequency of these events.

Example Output:
```
08:10:13.711 [lava-daemon-pool-info-loader-2-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackStartEvent
08:10:13.721 [lava-daemon-pool-playback-1-thread-3] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Starting to play track https://www.twitch.tv/speko037 locally with listener com.sedmelluq.discord.lavaplayer.player.AudioPlayer@4879e98
08:10:13.722 [lava-daemon-pool-playback-1-thread-3] DEBUG com.sedmelluq.discord.lavaplayer.source.twitch.TwitchStreamAudioTrack - Starting to play Twitch channel speko037.
08:10:13.722 [lava-daemon-pool-playback-1-thread-3] DEBUG com.sedmelluq.discord.lavaplayer.container.adts.AdtsAudioTrack - Starting to play ADTS stream https://www.twitch.tv/speko037
08:10:13.732 [lava-daemon-pool-playback-1-thread-1] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Playing track https://www.twitch.tv/monstercat finished or was stopped.
08:10:13.952 [JDA RateLimit-Queue Pool - Thread 1] DEBUG net.dv8tion.jda.core.requests.Requester - Received response with following cf-rays: [409d594c38299d14-AMS]
08:10:14.382 [lava-daemon-pool-playback-1-thread-3] DEBUG com.sedmelluq.discord.lavaplayer.source.twitch.TwitchStreamSegmentUrlProvider - Chose stream with quality chunked from url https://video-weaver.ams02.hls.ttvnw.net/v1/playlist/CtMCA2oz92usj9ttCS3OpAkU8QyACmqdwej_doe2BBQ0bAl6_5J-af_ptkjK5amAN4GJH_ZDY2AxDpDDPSi0lNqagWIfjFvvWfJMJ416yJHSr4hzk1qziO0AAiLpLNDNUPaNKxcWZKCI8mDkdIiJklUw5dxxY_Q7EVn3S8e0Ev1su6eocpN8VouHPTpcgZM5szaWQzUXh0ETimR-iZq28Hh3NN3oF_6Emb60EHWwsYHP8dhOQRXmgGqWMJuNEtLYM8G9680UiRD16DBnK2TR8qDwDrFE1Nv-u_3CZYli5nT_hH9_pvnRkmTI8viLWtq0Ie8DsoQpPfWjr5BB8z9CkaPIgpxgz2C55M7DQArlrWh7YqVYtM-GMlL6BBHoqdvVpBqi1d7C2at4DiT_T-k-vzClKvWiMIF9whGJHOaGzULnHc1DI1eQOCn1ec5se9n2kYQl0gQxEhCPdefGlDhhPuxBeBoBlajHGgxq5QO6SlwgCgadbOM.m3u8
08:26:59.736 [JDA AudioConnection Guild: 194794824371535873 Sending Thread] DEBUG com.sedmelluq.discord.lavaplayer.player.AudioPlayer - Firing an event with class TrackEndEvent
08:26:59.736 [lava-daemon-pool-playback-1-thread-3] DEBUG com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Playing track https://www.twitch.tv/speko037 finished or was stopped.
```

sedmelluq already fixed an issue with the same symptoms for Twitch streams, but i've been told that YouTube works completely different.

Either way, i wanted to put this out there, in case anyone has an idea.

**Comment by Bacon1153** [comment]
I have this same exact issue. YouTube live streams have always been super finicky for me; Often having long pauses where it seems it's buffering or something and I don't get this with anything else. An hour ago I had this REALLY strange occurrence where the live stream paused for five seconds and started spam adding the live stream (Which this has never ever happened before) and spat out this error:
``` 
[22:13:51] [ ERROR] [LocalAudioTrackExecutor] Error in playback of LsBrT6vbQa8
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:260)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.process(YoutubeMpegStreamAudioTrack.java:53)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStream(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:65)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Not success status code: 204
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:80)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:109)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:141)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:151)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:157)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.MpegReader.tryReadInt(MpegReader.java:133)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.MpegReader.nextChild(MpegReader.java:53)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:53)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.processSegmentStream(YoutubeMpegStreamAudioTrack.java:110)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.processNextSegment(YoutubeMpegStreamAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.execute(YoutubeMpegStreamAudioTrack.java:63)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.lambda$process$0(YoutubeMpegStreamAudioTrack.java:54)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
        ... 9 common frames omitted
```

**Comment by shikhir-arora** [comment]
Using the above livestream as an example, here's a verbose dump using youtube-dl for multiple video codecs: https://gist.github.com/shikhir-arora/900a3fd4fb90943beeec3dcf36ba1a10

All of the formats show an expiration of `1526203888`, which 05/13/2018 @ 9:31am (UTC) (about 6 hours from now).

**Comment by MCOfficer** [comment]
roughly two hours later, and the expiration has been updated to `1526211794` (11:43). apparently youtube always keeps the expiration 6 hours ahead. good idea, i'm not sure if lavaplayer checks for that or just takes the inital expiration.

(dump: https://gist.github.com/MCOfficer/4f7d42869af6b1a1f5d8e1d5e078fa0a, thank windows for the missing line endings)

**Comment by shikhir-arora** [comment]
Here's the last bit of output from ffmpeg (before I force-quit); this is using verbose mode on the same stream. I let it run for a while. https://gist.github.com/shikhir-arora/5edee567fcab79cd26c29e28c1459fb8#file-ffmpeg_out-sh-L55 At line 55 there, ffmpeg did have an error in the pull function (notice a few messages before that it also seems to handle repeating messages).

```
[tls @ 0x54dcc80] Error in the pull function.
[hls,applehttp @ 0x513ecc0] keepalive request failed for 'https://r1---sn-p5qs7n7z.googlevideo.com/videoplayback/id/LsBrT6vbQa8.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r1---sn-p5qs7n7z.googlevideo.com/ei/ot73WpqDCoWe8wT76qjACg/gcr/ca/playlist_type/DVR/initcwndbps/8100/mm/32/mn/sn-p5qs7n7z/ms/lv/mv/m/pl/53/beids/%5B9466594%5D/keepalive/yes/mt/1526193795/disable_polymer/true/ip/2607:5300:203:1202::/ipbits/0/expire/1526215426/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,gcr,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/96A33AF76929EA3BD6C7A70AEA1939C964C44846.60A0967BCA17045CC9087A7150757FDA4AAC6D28/key/dg_yt0/playlist/index.m3u8/sq/402182/goap/clen%3D48936%3Blmt%3D1526191689545613/govp/clen%3D524233%3Blmt%3D1526191689545624/dur/2.000/file/seg.ts', retrying with new connection: Input/output error
```

However, it resumed back as usual as shown.

**Comment by Bacon1153** [comment]
So apparently this is an issue with the live stream itself. I was playing the live stream on my bot while playing it in my browser and the live stream on both my bot and the website stopped. They even mention in chat they're having problems with their live stream.
![capture](https://user-images.githubusercontent.com/31748254/39968630-390ff93e-569e-11e8-9851-d85bec48b10e.PNG)

**Comment by Bacon1153** [comment]
Hmm, I tried a different stream and I'm still having live streams end prematurely even though it's continuing to play in YouTube. I even got a new error:
```
[11:55:10] [ ERROR] [LocalAudioTrackExecutor] Error in playback of ilxhlnDo7_M
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:260)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.process(YoutubeMpegStreamAudioTrack.java:53)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStream(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:65)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:357)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.MpegReader.nextChild(MpegReader.java:62)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:53)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.processSegmentStream(YoutubeMpegStreamAudioTrack.java:110)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.processNextSegment(YoutubeMpegStreamAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.execute(YoutubeMpegStreamAudioTrack.java:63)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.lambda$process$0(YoutubeMpegStreamAudioTrack.java:54)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
        ... 9 common frames omitted
Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at java.util.zip.InflaterInputStream.fill(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.util.zip.GZIPInputStream.read(Unknown Source)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:144)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:157)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.MpegReader.tryReadInt(MpegReader.java:133)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.MpegReader.nextChild(MpegReader.java:53)
        ... 15 common frames omitted
```

**Comment by MCOfficer** [comment]
respectfully, to me it seems like you are having a different issue.

**Comment by Bacon1153** [comment]
I have the same issue, but I also have a lot of additional issues lol.

**Comment by MCOfficer** [comment]
there's a difference between randomly ending the track and failing to decode it.

**Comment by MisterFixx** [comment]
Can confirm i'm having the same issue.
This is the livestream: https://youtu.be/HU1_KTNSj7k
The stream just randomly stops constantly.

**Comment by SoulSen** [comment]
Any update on fixes for this, or is it still being experienced?
