### ISSUE TITLE
OutOfMemoryError loading local file

### ISSUE THREAD

**Issue by xunkar** [sedmelluq/lavaplayer#119]
I am trying to play an Opus (in OGG) file of 1.8 MB but I get on "OutOfMemoryError: Java heap space" loading it. I tried starting the JVM with 1 GB of heap space (-Xms1g) but it is not enough, how is it possible?

> 19:02:30.432 [lava-daemon-pool-info-loader-2-thread-1] DEBUG c.s.d.l.c.o.OggContainerProbe - Track fillmoa.opus is an OGG stream.
19:02:30.484 [lava-daemon-pool-info-loader-2-thread-1] ERROR c.s.d.l.p.DefaultAudioPlayerManager - Error in loading item fillmoa.opus
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggOpusTrackProvider.getMetadata(OggOpusTrackProvider.java:65)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.collectStreamInformation(OggContainerProbe.java:65)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.probe(OggContainerProbe.java:46)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:76)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:45)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:46)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:33)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:432)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$110/15058813.call(Unknown Source)
	... 6 common frames omitted

I've confirmed that the bot is running correctly as I can play MP3 tracks without this issue.

**Comment by xunkar** [comment]
My mistake, something obviously wrong with the file, problably encoding issues.

**Comment by napstr** [comment]
The file was probably fine, there was an issue with excessive memory allocations when parsing opus-ogg files which has been solved in 1.3.8 (see https://github.com/sedmelluq/lavaplayer/pull/131)
