### ISSUE TITLE
I adapted the JDA demo to my existing JDA bot and it gives this error:

### ISSUE THREAD

**Issue by zCri** [sedmelluq/lavaplayer#120]
Exception in thread "main" java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:105)
	at me.zcri.bot.music.audioCommand.<init>(audioCommand.java:27)
	at me.zcri.bot.core.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

It's a runtime error

**Comment by BenjaminUrquhart** [comment]
Same

**Comment by FlashOnFire** [comment]
How do you import JDA ? Obviously, it isn't exported into the jar. You may need the maven shade plugin if you use maven. You can also open the jda jar and your exported file in winrar, then  copy all thr contents of the jda jar into your jar.

**Comment by BenjaminUrquhart** [comment]
I'm not sure what that has to do with the issue at hand. The issue involves LavaPlayer, not JDA

**Comment by sedmelluq** [comment]
Dependency load issue.
