### ISSUE TITLE
Common-io NoSuchMethodError - org.apache.commons.io.IOUtils.readFully

### ISSUE THREAD

**Issue by mkcoldwolf** [sedmelluq/lavaplayer#127]
```
19:17:31 [嚴重] Exception in thread "lava-daemon-pool-playback-1-thread-1"
19:17:31 [嚴重] java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:73)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:68)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:77)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
19:17:31 [嚴重]     at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
19:17:31 [嚴重]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19:17:31 [嚴重]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19:17:31 [嚴重]     at java.lang.Thread.run(Unknown Source)
19:17:54 [嚴重] Exception in thread "lava-daemon-pool-playback-1-thread-2"
19:17:54 [嚴重] java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:73)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.fragmented.MpegFragmentedFileTrackProvider.provideFrames(MpegFragmentedFileTrackProvider.java:68)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:77)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
19:17:54 [嚴重]     at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
19:17:54 [嚴重]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19:17:54 [嚴重]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19:17:54 [嚴重]     at java.lang.Thread.run(Unknown Source)
```

It seems that the version of common-io is not same with the one using with lava-player, which version should i use?
btw this happen when i playing some youtube that have only a few views, it wont play but it show that the music is played sucuess :L , in video that has large views dont have this problem :L what should i do?

**Comment by mkcoldwolf** [comment]
Solved! It was my other Maven Dependencies used the old version of Apache Common io
Also, Maven wont update the packe if old version is already shaded into jar, so when you have other depend that uses common io too, you have to put the depend code above, for me, its was bukkit, so

```
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-lang3</artifactId>
	<version>3.8.1</version>
</dependency>
<dependency>
	<groupId>org.bukkit</groupId>
	<artifactId>bukkit</artifactId>
	<version>1.8.8-R0.1-SNAPSHOT</version>
	<scope>provided</scope>
</dependency>
```
