### ISSUE TITLE
ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory

### ISSUE THREAD

**Issue by pablo67340** [sedmelluq/lavaplayer#129]
Title says it all.

It is throwing

`[11:16:07 WARN]: [Server thread] INFO JDA - Login Successful!
[11:16:07 ERROR]: Error occurred while enabling DiscordLink v0.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:105) ~[?:?]
        at website.bryces.discordlink.listenables.MusicListener.<init>(MusicListener.java:29) ~[?:?]
        at website.bryces.discordlink.main.Main.onEnable(Main.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[minecraft.jar:git-Spigot-fe3ab0d-bfb9131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 14 more`

This is on version 1.3.7. Any fix?

**Comment by MCOfficer** [comment]
#124

**Comment by pablo67340** [comment]
Came up with a temporary fix.

Add these 2 source files to your project, ensure they are in the correct folders. 

https://www.dropbox.com/s/xdh7yt5l6aa4pjs/Daemon.zip?dl=0

They must go into your src>com>sellmelluq>discord>lavaplayer>tools

**Comment by sedmelluq** [comment]
This is an issue with your dependency resolution. If, for some reason, there is some machinery there which expects each package to be present only in one JAR file, then changes in `1.3.11` will help. Otherwise you need to make sure the `lavaplayer-common` dependency gets loaded too.
