### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jsoup/nodes/Element

### ISSUE THREAD

**Issue by IanSloat** [sedmelluq/lavaplayer#148]
I used the temporary fix to the DaemonThreadFactory error as described in a previous issue and it worked but now it is throwing this exception
`java.lang.NoClassDefFoundError: org/jsoup/nodes/Element
	at com.sedmelluq.discord.lavaplayer.source.AudioSourceManagers.registerRemoteSources(AudioSourceManagers.java:33)
	at com.sedmelluq.discord.lavaplayer.source.AudioSourceManagers.registerRemoteSources(AudioSourceManagers.java:22)
	at main.IanSloat.thiccbot.Events.onMessageReceived(Events.java:104)
	at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:680)
	at sx.blah.discord.api.events.EventDispatcher.lambda$null$17(EventDispatcher.java:610)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.jsoup.nodes.Element
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more`

**Comment by napstr** [comment]
Why not just use a proper build tool / dependency management?

**Comment by IanSloat** [comment]
Probably should do that. Just haven’t yet. I’ll try that and see if it helps

**Comment by IanSloat** [comment]
Yes the problem was just me being dumb and not using maven. Everything works now
