### ISSUE TITLE
Can't play the .m3u8

### ISSUE THREAD

**Issue by cotwo0139** [sedmelluq/lavaplayer#152]
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:269)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsAudioTrack.process(AdtsAudioTrack.java:36)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:53)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
2018-12-12 21:29 +09:00: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-12-12 21:29 +09:00: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-12-12 21:29 +09:00: 	at java.lang.Thread.run(Thread.java:748)
2018-12-12 21:29 +09:00: Caused by: java.lang.IllegalStateException: Expected decoding to halt, got: 16388
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.resolveStreamInfo(AacDecoder.java:196)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.decodeAndSend(AdtsStreamProvider.java:93)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.provideFrames(AdtsStreamProvider.java:81)
2018-12-12 21:29 +09:00: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
2018-12-12 21:29 +09:00: 	... 8 common frames omitted

**Comment by cotwo0139** [comment]
Play URL: https://manifest.googlevideo.com/api/manifest/hls_playlist/id/rLMHGjoxJdQ.1/itag/91/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D139/sgovp/gir%3Dyes%3Bitag%3D160/hls_chunk_host/r7---sn-ab02a0nfpgxapox-jwwl.googlevideo.com/playlist_type/DVR/ei/JvsQXMTGHMSSgQOP3bmICg/gcr/kr/initcwndbps/12920/mm/32/mn/sn-ab02a0nfpgxapox-jwwl/ms/lv/mv/m/pl/18/usequic/no/dover/11/keepalive/yes/mt/1544616631/disable_polymer/true/ip/182.209.5.10/ipbits/0/expire/1544638342/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,ei,gcr,initcwndbps,mm,mn,ms,mv,pl,usequic/signature/1A286567233888C0B4EDDCF0E183A46A4344E535.7F5E08E65CFE81FDCCF1AD16DC57219DD08ED063/key/dg_yt0/playlist/index.m3u8

**Comment by CorruptComputer** [comment]
I think this may be due to the permissions on the file hosted at that link. I cannot access it, so lavaplayer would most likely not be able to either.

**Comment by cotwo0139** [comment]
> I think this may be due to the permissions on the file hosted at that link. I cannot access it, so lavaplayer would most likely not be able to either.

Thanks! I missed it
