### ISSUE TITLE
vServer Error by play cmd: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Seblofs** [sedmelluq/lavaplayer#160]
byte[] data;
        data = lastFrame != null ? lastFrame.data : null;
        lastFrame = null;
        return data;
by lastFrame.data it says, "Cannot resolve data"

**Comment by MCOfficer** [comment]
Can you be more specific? Provide a full Error or Stacktrace, format your question and give more context.

**Comment by Seblofs** [comment]
This came, when I try to start the Bot:
Error:(32, 45) java: cannot find symbol
  symbol:   variable data
  location: variable lastFrame of type com.sedmelluq.discord.lavaplayer.track.playback.AudioFrame

**Comment by Seblofs** [comment]
here it the error:
byte[] data;
        data = lastFrame != null ? lastFrame.**data** : null;
        lastFrame = null;
        return data;

**Comment by Seblofs** [comment]
.getData() works, ok but when i like to play music it didn`t work. Here my /play code:
```
case "play":
            case "p":
                String input = String.join(" ", Arrays.copyOfRange(args, 1, args.length));
                if (input != null && input.startsWith("http"))
                STATIC.input = input;
                else
                   input = "ytsearch: " + input;

                if (args.length  <= 1) {
                    sendErrorMsg(event, "Bitte gebe ein gültigen Link an!");

                } else {
                    loadTrack(input, event.getMember(), event.getMessage());

                    if (getPlayer(guild).isPaused())
                        getPlayer(guild).setPaused(false);

                    new Timer().schedule(
                            new java.util.TimerTask() {
                                @Override
                                public void run() {
                                    int tracks = getManager(guild).getQueuedTracks().size();
                                    sendSuccsesMsg(event, "`" + tracks + "` Tracks zur Warteschleife hinzugefügt.");
                                }
                            },
                            5000
                    );
                }
                break;
```

**Comment by Devoxin** [comment]
`didn't work` is very vague. I'm going to assume you mean there's no audio playback, in which case you need to make sure you've registered your sending handler.

**Comment by Seblofs** [comment]
Ok now on my PC it works but when i try to play music on the vServer this error came:
ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException
        at listeners.logListener.onMessageReceived(logListener.java:36)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:410)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:127)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:994)
        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:892)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:871)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1029)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by Seblofs** [comment]
now it work on my pc but on my vserver this error came:
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1974)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:345)
        at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339)
        at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968)
        at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
        at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
        at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1098)
        at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
        at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:60)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:112)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:149)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:165)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)

**Comment by Seblofs** [comment]
Java Version 10.0.2

**Comment by Seblofs** [comment]
After i reset the vServer, it works
