### ISSUE TITLE
"java.lang.NullPointerException: null" on AudioPlayer.provide(MutableAudioFrame)

### ISSUE THREAD

**Issue by emre1702** [sedmelluq/lavaplayer#168]
Hello, I'm using Discord4J (3.0.1) and the LavaPlayer demo for D4J.
When I start playing a track, I get a huge spam with the ERROR (nearly 100KB in log file).
After a short time (nearly 1 second) the song starts to play and the spam stops.

`boolean didProvide = player.provide(frame);`

> 23:48:22.371: [ERROR][elastic-2][reactor.core.scheduler.Schedulers] - Scheduler worker in group main failed with an uncaught exception
java.lang.NullPointerException: null
        at com.sedmelluq.discord.lavaplayer.track.playback.AllocatingAudioFrameBuffer.passToMutable(AllocatingAudioFrameBuffer.java:107) ~[lavaplayer-1.3.14.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.playback.AllocatingAudioFrameBuffer.provide(AllocatingAudioFrameBuffer.java:95) ~[lavaplayer-1.3.14.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.provide(LocalAudioTrackExecutor.java:412) ~[lavaplayer-1.3.14.jar:?]
        at com.sedmelluq.discord.lavaplayer.track.BaseAudioTrack.provide(BaseAudioTrack.java:102) ~[lavaplayer-1.3.14.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:234) ~[lavaplayer-1.3.14.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:214) ~[lavaplayer-1.3.14.jar:?]
        at bonusbot.audio.lavaplayer.LavaplayerAudioProvider.provide(LavaplayerAudioProvider.java:22) ~[bonusbotNew.jar:?]

**Comment by sedmelluq** [comment]
Should be fixed on `1.3.16`.
