### ISSUE TITLE
[lava-daemon-pool-playback-1-thread-2] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of e1HrZAuIzKU

### ISSUE THREAD

**Issue by Seblofs** [sedmelluq/lavaplayer#175]
It works long but suddenly this error came, when i try ytsearch. 
When i input the Link it works, but the ytsearch doesn`t work any longer:

[lava-daemon-pool-playback-1-thread-2] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of e1HrZAuIzKU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:149)
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:165)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        ... 4 more

**Comment by Dramex** [comment]
Same issue here.

**Comment by HysteriaMC** [comment]
same

**Comment by Jonbeckas** [comment]
same

**Comment by Dramex** [comment]
I fixed this by upgrading to dev version.15.06.2019, 17:50, "Jonbeckas" <notifications@github.com>:same

**Comment by Jonbeckas** [comment]
how did i do this

**Comment by craftxbox** [comment]
@Dramex, What dev release are you talking about? There is only the master branch...

**Comment by Dramex** [comment]
@Jonbeckas @craftxbox 
https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&tab=buildTypeStatusDiv&branch_Lavalink=refs%2Fheads%2Fdev

**Comment by Dramex** [comment]
@Jonbeckas @craftxbox 
it's stable now, just upgrade your lavaplayer version to 1.3.17

**Comment by craftxbox** [comment]
That CI requires registration, do you have a link to a public one?

**Comment by Dramex** [comment]
@craftxbox nvm, just upgrade your lavaplayer to latest version and that will fix it.

**Comment by craftxbox** [comment]
I am running 1.3.17 right now, and where i'm getting the issue.

**Comment by Jonbeckas** [comment]
I have the same problen on the newest version
