### ISSUE TITLE
Problem with getting packet

### ISSUE THREAD

**Issue by SlamaFR** [sedmelluq/lavaplayer#176]
So, I'm getting random ConcurrentModificationException while playing music in some guild.

I'm using LavaPlayer `1.3.16`.

I don't know why this is going on, but there is the complete stack trace:
```
01-06-19 12:02:44 ERROR n.d.j.core.audio.AudioConnection - There was an error while getting next audio packet
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:348)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.handleTerminator(DefaultAudioPlayer.java:260)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:196)
        at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)   
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:175)
        at fr.slama.yeahbot.music.AudioHandler.canProvide(AudioHandler.java:22)
        at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:662)
        at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:652)
        at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
        at java.lang.Thread.run(Thread.java:748)
```

Pretty sure this is not my fault, but because I'm still wondering, there is the `canProvide()`:
```java
@Override
public boolean canProvide() {
    lastFrame = audioPlayer.provide();
    return lastFrame != null;
}
```

**Comment by SlamaFR** [comment]
Problem fixed. Turned out I was removing listener and destroying `MusicPlayer` at the same time.
