### ISSUE TITLE
Soundcloud: Error in playback 189559327

### ISSUE THREAD

**Issue by ElectricReality** [sedmelluq/lavaplayer#187]
Server Logs: https://pastebin.com/Q2DpHnyx
Song trying to play : shigatsu wa kimi no uso

**Comment by sedmelluq** [comment]
Does it happen for all tracks or just this specific one?

**Comment by ElectricReality** [comment]
Just this specific one

**Comment by aikaterna** [comment]
I am a Lavalink user, although my jar is using Lavaplayer 1.3.19. I can reproduce this by passing the string `shigatsu wa kimi no uso` as a Soundcloud search using the scsearch: endpoint and enqueing the result of: https://soundcloud.com/fanzen190/shigatsu-wa-kimi-no-uso
That url will generate this error but other Soundcloud tracks returned for the scsearch for "shigatsu wa kimi no uso" seem to play with no issues. There is also not a login prompt on the Soundcloud page for the url that is affected, or otherwise showing why that track is throwing a 401 unauthorized.

```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) [lavaplayer-1.3.19.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: java.lang.RuntimeException: Not success status code: 401
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:169) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:185) ~[lavaplayer-1.3.19.jar!/:na]
	at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[na:1.8.0_212]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.skipIdv3Tags(Mp3TrackProvider.java:194) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:75) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.attemptLoadStream(SoundCloudAudioTrack.java:61) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:41) ~[lavaplayer-1.3.19.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[lavaplayer-1.3.19.jar!/:na]
	... 4 common frames omitted
```

**Comment by sedmelluq** [comment]
Unable to reproduce anymore, likely to be fixed among various SoundCloud fixes since reporting.
