### ISSUE TITLE
"FriendlyException: This url does not appear to be a playable track." for valid soundcloud URLs.

### ISSUE THREAD

**Issue by robinfriedli** [sedmelluq/lavaplayer#209]
Hi

Since last Thursday, the 5th of September, I am getting errors when attempting to load soundcloud URLs. I have verfied that this occurs for links that used to work and definitely point to a valid soundcloud track or playlist. Maybe soundcloud moved some things around that require updating how the JSON is parsed?

```
[ERROR] 2019-09-08 23:00:03.593 [lava-daemon-pool-info-loader-2-thread-1] UrlAudioLoader - lavaplayer threw an exception while loading track https://soundcloud.com/linkin_park/numb
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadPageConfigJson(SoundCloudAudioSourceManager.java:327) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:291) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:266) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:119) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.20.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.20.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Shadorc** [comment]
Hi, try with the latest version 1.21

**Comment by MCOfficer** [comment]
^ specifically, #208

**Comment by robinfriedli** [comment]
Yup! I guess I was just a bit early :)
