### ISSUE TITLE
Systematic error : Unable to play this YouTube track

### ISSUE THREAD

**Issue by farlistener** [sedmelluq/lavaplayer#211]
Hi, 

since few hours I've got this error :

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unable to play this YouTube track.
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadTrackFormats(YoutubeAudioTrack.java:140)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:98)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:62)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: No adaptive formats, no dash, no stream map.
	... 8 more

An idea ? A change in youtube ?

**Comment by BenjaminUrquhart** [comment]
See https://github.com/sedmelluq/lavaplayer/pull/210

**Comment by farlistener** [comment]
thanks, was not open, didn't see it

**Comment by Fabricio20** [comment]
This issue is not the same as reported on #203  (and fixed by PR #210 ).

Seems like it's related to new formats that are being served in some regions (US-EAST?). Youtube-DL seems to have pushed a [fix](https://github.com/ytdl-org/youtube-dl/commit/bf1317d257d13188601c837c983830355c6203e5) already.

**Comment by BenjaminUrquhart** [comment]
@Fabricio20 my bad

**Comment by sedmelluq** [comment]
Does not seem to be relevant anymore.
