### ISSUE TITLE
InterruptedException when attampting to play audio from soundcloud

### ISSUE THREAD

**Issue by R3alCl0ud** [sedmelluq/lavaplayer#22]
Every time I attempt to start playing audio from soundcloud I get this error when calling
`AudioFrame frame = this.connection.player.provide();`
[The line in my code thats throwing the error](https://github.com/R3alCl0ud/DiscLoader/blob/master/src/main/java/io/discloader/discloader/network/voice/StreamProvider.java#L71)
The error seems to originate at [Line 18](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/track/playback/AudioFrameProviderTools.java#L18) in [AudioFrameProviderTools.java](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/track/playback/AudioFrameProviderTools.java), or atleast thats the deepest point printed in the stack trace.
```
[17:16:39] [DiscLoader/SEVERE]: java.lang.RuntimeException: java.lang.InterruptedException
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:21)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
[17:16:39] [DiscLoader/SEVERE]: at io.discloader.discloader.network.voice.StreamProvider.getNextPacket(StreamProvider.java:72)
[17:16:39] [DiscLoader/SEVERE]: at io.discloader.discloader.network.voice.StreamSender$1.run(StreamSender.java:36)
[17:16:39] [DiscLoader/SEVERE]: Caused by: java.lang.InterruptedException
[17:16:39] [DiscLoader/SEVERE]: at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(Unknown Source)
[17:16:39] [DiscLoader/SEVERE]: at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(Unknown Source)
[17:16:39] [DiscLoader/SEVERE]: at java.util.concurrent.ArrayBlockingQueue.poll(Unknown Source)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameBuffer.provide(AudioFrameBuffer.java:106)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.provide(LocalAudioTrackExecutor.java:353)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.track.BaseAudioTrack.provide(BaseAudioTrack.java:95)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:190)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
[17:16:39] [DiscLoader/SEVERE]: at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
[17:16:39] [DiscLoader/SEVERE]: ... 3 more
```
I'm using version 1.2.27 if that helps.

**Comment by sedmelluq** [comment]
It seems as if something is calling `Thread#interrupt()` on that thread. The library itself should only ever trigger interrupts on the threads which fill the audio buffers, so I can't think of how it could be the cause.

If you can reproduce it locally, maybe you can set a breakpoint on `Thread#interrupt()` to see what is calling it for that thread?

**Comment by R3alCl0ud** [comment]
I can reproduce it every time, and it happens on both my Desktop(running win10 and jdk1.8_121) and my macbook pro (running jdk1.8_60)

**Comment by R3alCl0ud** [comment]
Well I figured out the cause, There was multiple threads trying to call `<AudioPlayer>.provide()` to send the next packet to the udpSocket. But, it just fails to load tracks from soundcloud alltogether now.

**Comment by R3alCl0ud** [comment]
So, I figured out that tracks from Sound Cloud need some time before they can be played.

**Comment by sedmelluq** [comment]
Still does not resolve your core problem that at the moment you call `.provide()`, your thread is in the interrupted state. The code which throws the actual exception:
```java
        if (Thread.interrupted())
            throw new InterruptedException();
```
While your thread is in that state, any blocking operation may throw an exception like that.

**Comment by R3alCl0ud** [comment]
Ok, but while I was running through the stack trace in debug with the break point I set I noticed that if a [SoundCloudAudioTrack](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/soundcloud/SoundCloudAudioTrack.java) is played as soon as [`AudioLoadResultHandler#trackLoaded(AudioTrack track)`](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/player/AudioLoadResultHandler.java#L15) is called it hasn't started to load the audio and ends with `LOAD_FAILED` before beginning to load the audio. I noticed this because `AudioPlayer#provide()` wasn't throwing the error until it had been called like 13~16 times, and each of those times it returned a `terminator` frame. But if I put a youtube track in before the soundcloud track and let it play through the youtube one, it was able to load the one from soundcloud.

**Comment by R3alCl0ud** [comment]
also I don't start calling `AudioPlayer#provide()` until after `AudioEventAdapter#onTrackStart()` is called

**Comment by sedmelluq** [comment]
If you ever get `LOAD_FAILED`, get the stack trace as well. Terminator frame is only produced once per track (and is consumed by AudioPlayer internally).

Did you ever find what was interrupting that thread though?

**Comment by R3alCl0ud** [comment]
I'm pretty sure that my code was borked and was trying to call `AudioPlayer#provide()` several times before `AudioPlayer#provide()` was able to return an `AudioFrame` for any of the calls.

Either way I have already fixed the issue on my end, so I'm going to close this issue.
