### ISSUE TITLE
Soundcloud broken again

### ISSUE THREAD

**Issue by robinfriedli** [sedmelluq/lavaplayer#231]
Soundcloud URLs appear to have stopped working again similar to #209  using the latest version. Both with 1.3.22.pbjtest3 and 1.3.22 I get the same exception.
```
[ERROR] 2019-10-13 23:07:16.628 [lava-daemon-pool-info-loader-2-thread-1] UrlAudioLoader - lavaplayer threw an exception while loading track https://soundcloud.com/leagueoflegends/legends-never-die
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadPageConfigJson(SoundCloudAudioSourceManager.java:327) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:291) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:266) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:119) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.22.pbjtest3.jar:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Shadorc** [comment]
There is already a PR open to fix this issue: https://github.com/sedmelluq/lavaplayer/pull/229
