### ISSUE TITLE
LavaPlayer YouTube request starting to get rate limited

### ISSUE THREAD

**Issue by robinfriedli** [sedmelluq/lavaplayer#233]
Hi

I've recently started to run into an issue where YouTube requests made by lava player start running into a 429 TooManyRequests response. This keeps happening even when I stop the bot and start a private instance with almost no traffic. The only way to fix this seems to be by changing the server instance's public IP, then all requests work again even under peak traffic until they don't and then the cycle repeats. Is that part of YouTube trying to shutdown music bots?

```
[ERROR] 2019-10-15 08:59:25.572 [lava-daemon-pool-info-loader-2-thread-1] UrlAudioLoader - lavaplayer threw an exception while loading track https://www.youtube.com/watch?v=YLHpvjrFpe0
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:233) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:323) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromMainDomain(YoutubeAudioSourceManager.java:260) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:330) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.22.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: Invalid status code for video info response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:401) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:390) ~[lavaplayer-1.3.22.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:201) ~[lavaplayer-1.3.22.jar:?]
        ... 12 more
```

**Comment by Shadorc** [comment]
You can see the message provided by Google when getting rate limited here: https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3D9Zj0JOHJR-s&amp;q=EgQzD-b4GIv78-wFIhkA8aeDS7PYOFQwMbyfmiCqfdbmr3HKsT6uMgFy#

It says that the rate limit will stop ONLY after all requests have stopped during a short amount of time.
A pull request draft is alreayd open to try to solve this issue: https://github.com/sedmelluq/lavaplayer/pull/232

**Comment by robinfriedli** [comment]
It also mentions that the response could be caused by detected violation of the terms and services. I fear that might be the case as YouTube is trying to [shut down music bots again](https://www.reddit.com/r/discordapp/comments/dgn84b/psa_youtubegoogle_blocked_all_music_bots_again/?utm_medium=android_app&utm_source=share). I couldn't find any exact specification about after how much time the rate limit should expire, but I once completely shut down and restarted the server, which should be plenty of time for the rate limit to reset, yet the requests were still blocked.

**Comment by Shadorc** [comment]
I have stopped requesting data to YouTube for several hours and get unblocked but I don't know the exact elapsed time.

**Comment by Mtik333** [comment]
> 
> 
> Hi!
> You can see the full message and the explanation provided by Google when getting rate limited here: https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3D9Zj0JOHJR-s&amp;q=EgQzD-b4GIv78-wFIhkA8aeDS7PYOFQwMbyfmiCqfdbmr3HKsT6uMgFy#
> 
> It says that the rate limit will stop ONLY after all requests have stopped during a short amount of time.
> 
> A pull request draft is already open to try to solve this issue: #232

Has this problem been resolved in some way? Or is it possible to provide the value from "Retry-After" header sent from YouTube in the exception message?

**Comment by MCOfficer** [comment]
Checking the linked PR leads you [here](https://github.com/sedmelluq/lavaplayer/pull/232#issuecomment-550274926).

**Comment by Shadorc** [comment]
@Mtik333 The two current solutions are either to stop requesting YouTube videos for an unknown amount of time (generally several hours / days) or to use IP rotation like MCOfficer linked.

**Comment by Mtik333** [comment]
> 
> 
> @Mtik333 The two current solutions are either to stop requesting YouTube videos for an unknown amount of time (generally several hours / days) or to use IP rotation like MCOfficer linked.

Thanks, I'll try to find out how to use this IP rotation.
