### ISSUE TITLE
Doesn't play song on RaspberryPi 4 with Java 11.0.5

### ISSUE THREAD

**Issue by BennoDev1** [sedmelluq/lavaplayer#251]
I have the same error like **two other people here** but on a RasberryPi 4 and the solution occured doesn't work in my case

`Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: 'long com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(int, int)'
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(Native Method)
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:188)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:172)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:91)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:78)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:70)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

![grafik](https://user-images.githubusercontent.com/57860196/69006114-f9a77880-092a-11ea-9cf3-9f151ba3e623.png)

I also tried to update Java on the RaspberryPi 4 to 13.0.1 because with this version it works on my WindowsEngine but this is nearly inpossible to install Java 13.0.1 to the Pi :/

Thank you

**Comment by MCOfficer** [comment]
#16 - tl;dr: ARM is not officially supported, either build the libraries yourself or get them from somewhere else. Your java version is not the issue.

**Comment by RakSrinaNa** [comment]
For the Java versions, I use Bellsoft builds and can be installed easily on the Pi with apt. Concerning the so file, I managed to make it work through a dependency: https://github.com/natanbc/lavaplayer-arm-natives

**Comment by BennoDev1** [comment]
Yeah,
https://mvnrepository.com/artifact/com.github.natanbc/lavaplayer-arm-natives/1.3.10
With the lavaplayer-arm-natives imported with Maven it works ^^
Thank you guys
