### ISSUE TITLE
Youtube playback NPE (1.3.32)

### ISSUE THREAD

**Issue by duncte123** [sedmelluq/lavaplayer#258]
When playing a video that has no available streams lavaplayer throws a NullPointerException
```
19-12-2019 21:05:31 lava-daemon-pool-playback-1-thread-2  LocalAudioTrack ERROR  Error in playback of sRDl_UP-qeg
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
	... 4 common frames omitted
```

**Comment by duncte123** [comment]
Unavailable videos to test the fix with: 
https://youtu.be/TyBlkZRMG2g
https://youtu.be/sRDl_UP-qeg
