### ISSUE TITLE
Number format exception during lookup for "lofi-beats"

### ISSUE THREAD

**Issue by IamDwight** [sedmelluq/lavaplayer#275]
```
[ERROR] 2020-02-23 16:27:28.124 [lava-daemon-pool-info-loader-2-thread-1] DefaultAudioPlayerManager - Error in loading item ytsearch:lofi-beats
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226) ~[IcarusPublicBot-1.1-all.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) [IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) [IcarusPublicBot-1.1-all.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by IamDwight** [comment]
Additionally receive this stack, with it:
```Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "13,165"
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:57) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:255) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:228) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:34) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:133) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[IcarusPublicBot-1.1-all.jar:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[IcarusPublicBot-1.1-all.jar:?]
        ... 6 more

**Comment by IamDwight** [comment]
Further, I see why this is happening.  I've searched "lofi-beats" in YouTube myself on my browser, and it shows results like these:
![Vkmuj](https://user-images.githubusercontent.com/3433941/75120684-418d1880-565b-11ea-86f4-30652b91556f.png)
Notice the odd timestamp on the videos I marked

**Comment by sedmelluq** [comment]
Fixed.
