### ISSUE TITLE
Error on Run

### ISSUE THREAD

**Issue by SaltJuice** [sedmelluq/lavaplayer#30]
Got this error and its preventing the bot from running, the method is in there, and without any errors

Exception in thread "main" java.lang.NoSuchMethodError: com.sedmelluq.discord.lavaplayer.tools.ExecutorTools.createEagerlyScalingExecutor(IIJLjava/lang/String;)Ljava/util/concurrent/ExecutorService;
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:91)
	at dAndroid.dAndroid2.<init>(dAndroid2.java:335)
	at dAndroid.dAndroid2.main(dAndroid2.java:51)

**Comment by sedmelluq** [comment]
Looks like it's incorrectly packaged. One version which was the latest for a very short time also legitimately had this issue, but that was fixed very quickly. Closing.
