### ISSUE TITLE
Playing certain YouTube videos causes an exception

### ISSUE THREAD

**Issue by totietje** [sedmelluq/lavaplayer#39]
I get the following exception:

```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Must find action functions from script.
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractTokensFromScript(YoutubeSignatureCipherManager.java:164)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:129)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:88)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:99)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	... 4 more
```

So far, the only video this has happened with is `https://www.youtube.com/watch?v=tG35R8F2j8k`. Every time I try and play this video, this exception gets thrown.

**Comment by davue** [comment]
Can confirm. I also tried using youtube-dl. It too failed with version 2017.05.14 but was fixed in 2017.05.18. This was most likely the fix for the problem: https://github.com/rg3/youtube-dl/commit/7769f837018cbfa6cab615b8ae938528f895ce8c

**Comment by Frederikam** [comment]
YouTube changed some things on their end. This was fixed in `1.2.39`.

**Comment by davue** [comment]
Oh ok it seems like we missed this release ^^

**Comment by totietje** [comment]
I didn't miss this release, I just forgot to refresh my grade before trying it out (I'm an idiot). Sorry!
