### ISSUE TITLE
 Required library at /natives/linux-arm/libconnector.so was not found: Rpi3(Raspian 8)

### ISSUE THREAD

**Issue by derpmcgerp1080p** [sedmelluq/lavaplayer#41]
Hello,

I'm encountering an issue with running the bot on a RPi3 as a JAR. It connects fine but once a track is queued for playback it errors out on missing dependencies:
`
[18:11:24] [Info] [JDA]: Login Successful!
[18:11:25] [Info] [JDASocket]: Connected to WebSocket
[18:11:25] [Info] [JDA]: Finished Loading!
[18:11:35] [Info] [JDAAudioManager]: Audio System successfully setup!
Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libconnector.so was not found
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93)
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:17)
        at com.sedmelluq.discord.lavaplayer.natives.vorbis.VorbisDecoderLibrary.getInstance(VorbisDecoderLibrary.java:13)
        at com.sedmelluq.discord.lavaplayer.natives.vorbis.VorbisDecoder.<init>(VorbisDecoder.java:19)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggVorbisTrackProvider.<init>(OggVorbisTrackProvider.java:33)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.chooseTrackFromIdentifier(OggTrackLoader.java:40)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.loadTrack(OggTrackLoader.java:31)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.processTrackLoop(OggAudioTrack.java:50)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.lambda$process$0(OggAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.process(OggAudioTrack.java:40)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:51)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

I used maven to built this bot and the same JAR functions fine on Windows systems.

**Comment by NachtRaben** [comment]
sedmelluq - 01/31/2017
the native libs for arm are not included by default
Adam - 01/31/2017
You're missing the lib connector
sedmelluq - 01/31/2017
here's one that someone has compiled for it: https://cdn.discordapp.com/attachments/263484072389640193/271640326890848256/libconnector.so
Tairoon - 01/31/2017
how do i fix it?
sedmelluq - 01/31/2017
put it into your classpath in natives/linux-arm

**Comment by Alphapcka-lgtm** [comment]
Hello,

I'm encountering the same problem. I've tried adding the libconnector (from the comment above) to java library path and directly adding it to the lib folder of my java installation but I still get the error.
