### ISSUE TITLE
Tracks not working [Something broke when playing the track]

### ISSUE THREAD

**Issue by Seblofs** [sedmelluq/lavaplayer#463]
```
[Commander] /m wurde von Sebi | Ibes | ToadOfs#1702 ausgef?hrt:  p keks
2020-04-12 13:06:47 [lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor  - Error in playback of e1HrZAuIzKU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Received non-success response code 404
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91)
        ... 4 more
java.lang.NullPointerException
        at commands.cmdMusic$4.run(cmdMusic.java:363)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)


```
Java Version: 13.0.2
OS: Ubuntu 16.04
LavaPlayer Version: 1.3.46

**Comment by Devoxin** [comment]
You are not using Lavaplayer 1.3.46.

This track works fine on 1.3.46. It is likely that you are using a version older than 1.3.38, as 1.3.38 introduced a fix for this.

**Comment by Seblofs** [comment]
![image](https://user-images.githubusercontent.com/40692731/79119110-d8d73800-7d8f-11ea-8f49-72c645965a94.png)

I'm pretty sure I'm using version 1.3.46
