### ISSUE TITLE
YouTube Mix playlist links w/ bad songs

### ISSUE THREAD

**Issue by aikaterna** [sedmelluq/lavaplayer#466]
This is an incredibly specific nitpick so I'm not really sure if it's worth addressing. Using Lavaplayer 1.3.47 in Lavalink.

Loading this url:  https://www.youtube.com/watch?v=FuAHR4lkjCo&list=RDFuAHR4lkjCo&start_radio=1

Gives this traceback:
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not find tracks from mix.
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMixProvider.load(YoutubeMixProvider.java:68) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:244) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:91) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.47.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.47.jar!/:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
```

The FriendlyException returned is `Could not find tracks from mix.` which is true as the page provides no mix tracks or other tracks to pull, but the exception I expected to see was `Video unavailable / This video contains content from SME, who has blocked it in your country on copyright grounds.` from the page/video that was returned (https://www.youtube.com/watch?v=FuAHR4lkjCo)

**Comment by aikaterna** [comment]
Linking to #259 as I originally reported that URL not working on that issue.

**Comment by aikaterna** [comment]
The appropriate string/error ("Video unavailable / This video contains content from SME, who has blocked it in your country on copyright grounds.") is provided on 1.3.50+, not sure what changed and when but this is resolved.
