### ISSUE TITLE
Tried using last version and this version and music just doesn't seem to want to load

### ISSUE THREAD

**Issue by Evesain** [sedmelluq/lavaplayer#467]
No matter what link i try and play it doesnt like it, not sure if its on youtube's end or if lava needs updating?

https://i.imgur.com/eX7bxhM.png

**Comment by duncte123** [comment]
That means you've been banned temporarily from youtube

**Comment by callmebackdraft** [comment]
i think the issue lies deeper, i havent used the player for a week+ and it still gives the same error on each lookup

**Comment by MCOfficer** [comment]
Are you sure it's the same error? A 429 is a clear "hold up buddy" from youtube, nothing on LP's end.

**Comment by callmebackdraft** [comment]
@MCOfficer snap you are right i missed reading that line, i am getting a 404
`2020-04-15 14:52:20.022  INFO 26096 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: final countdown
2020-04-15 14:52:27.326  INFO 26096 --- [   XNIO-2 I/O-8] lavalink.server.io.SocketServer          : {"volume":50,"guildId":"581592305971101745","op":"volume"}
2020-04-15 14:52:27.340  INFO 26096 --- [   XNIO-2 I/O-8] lavalink.server.io.SocketServer          : {"track":"QAAAlgIALUV1cm9wZSAtIFRoZSBGaW5hbCBDb3VudGRvd24gKE9mZmljaWFsIFZpZGVvKQAPZXVyb3BldGhlYmFuZHR2AAAAAAAEhEAACzlqSy1OY1JtVmN3AAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9OWpLLU5jUm1WY3cAB3lvdXR1YmUAAAAAAAAAAA==","startTime":0,"endTime":296000,"noReplace":false,"guildId":"581592305971101745","op":"play"}
2020-04-15 14:52:27.972  INFO 26096 --- [   XNIO-2 I/O-8] lavalink.server.io.SocketServer          : {"sessionId":"d434c8a1bd868c949b8b1f9a6f837258","guildId":"581592305971101745","event":{"token":"4ce996ab710b549e","endpoint":"eu-west473.discord.media:80"},"op":"voiceUpdate"}
2020-04-15 14:52:28.425 ERROR 26096 --- [back-5-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 9jK-NcRmVcw

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) [lavaplayer-1.3.22.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.io.IOException: Received non-success response code 404
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:155) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:140) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getValidUrl(YoutubeSignatureCipherManager.java:101) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:102) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[lavaplayer-1.3.22.jar!/:na]
        ... 4 common frames omitted`

**Comment by Devoxin** [comment]
If your issue is resolved, you can click the close issue button.
