### ISSUE TITLE
Multiple issues loading audio track

### ISSUE THREAD

**Issue by lost-illusi0n** [sedmelluq/lavaplayer#493]
The video- https://www.youtube.com/watch?v=iKgmSeHW1UI
When trying to load it by using the identifier "ytsearch: pitbull songs", it often can not find any track. However when it does find the track and you select the one called "The Best Songs of Pitbull 2018 full playlist", I get this error 
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unable to play this YouTube track.
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadTrackFormats(YoutubeAudioTrack.java:136)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:96)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:60)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalStateException: No adaptive formats, no dash, no stream map.
```
When I just directly pass in a url as the identifier I get this as an error, 
```
Caused by: java.lang.NullPointerException
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:210)
```

This is the handler I currently use to query and play
```kotlin
playerManager.loadItem(query, object : AudioLoadResultHandler {
    override fun loadFailed(exception: FriendlyException) { handle exception }

    override fun noMatches() { handle exception }

    override fun trackLoaded(track: AudioTrack) {
        if (audioQueue.peek() == null) player.playTrack(track)
        audioQueue.add(track)
        future.complete(track)
    }

    override fun playlistLoaded(playlist: AudioPlaylist) {
        val tracks = playlist.tracks
        if (playlist.isSearchResult) {
            simplified select logic to selectSearchResults
            selectSearchResults(tracks).thenAccept {
                val selectedTrack = tracks[it]
                if (audioQueue.peek() == null) player.playTrack(selectedTrack)
                    audioQueue.add(selectedTrack)
                    future.complete(selectedTrack)
                }.exceptionally { e ->
                    //handle none selected
                }
            }
        } else {
            if (audioQueue.peek() == null) player.playTrack(tracks.first())
            audioQueue.addAll(tracks)
            future.complete(playlist)
        }
    }
})
```

My PlayerLibrary version is 1.3.5.

**Comment by duncte123** [comment]
You're way outdated as the current version is `1.3.50`, try that version

**Comment by lost-illusi0n** [comment]
damn, sorry bout that. didn't even think of double checking the version again as it seemed to be just that one link. thanks 😅
