### ISSUE TITLE
Getting weird errors when playing back from soundcloud

### ISSUE THREAD

**Issue by cloudybyte** [sedmelluq/lavaplayer#499]
idk if it helps, but this is the song I tried to play: https://soundcloud.com/rin-official/dior-2001

```
12:46:06.952 [lava-daemon-pool-playback-1-thread-1] ERROR: Error in playback of M:https://api-v2.soundcloud.com/media/soundcloud:tracks:654897911/4916ffd2-bf48-43a5-935e-814f6053dce7/preview/progressive
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:294)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:36)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.loadFromMp3Url(SoundCloudAudioTrack.java:83)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:60)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.io.EOFException
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.provideFrames(Mp3TrackProvider.java:139)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276)
        ... 11 more
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.fillFrameBuffer(Mp3FrameReader.java:114)
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.provideFrames(Mp3TrackProvider.java:119)
        ... 12 more
```

**Comment by cloudybyte** [comment]
the songs starts for like 5-10s and then the error occurs and the playback stops

**Comment by Devoxin** [comment]
EOF exceptions happen when you try and play a "premium" song -- SC serves a 30 second clip and then cuts the data stream, hence "end of file exception". Not really an issue per se.

**Comment by duncte123** [comment]
Some digging into the sound cloud json gave me `"snipped":true`
Maybe that can be used to see if the track cuts off after 30 seconds

**Comment by cloudybyte** [comment]
Well, can't do anything about it...
Closing the issue
