### ISSUE TITLE
NullPointerExpection when searching YouTube

### ISSUE THREAD

**Issue by Gregyyy** [sedmelluq/lavaplayer#501]
When I use YoutubeSearchProvider#loadSearchResult a get this NullPointerException:

```
java.lang.RuntimeException: java.lang.NullPointerException
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:74)
	*** INTERNAL COMMAND HANDELING ***
Caused by: java.lang.NullPointerException: null
	at com.sedmelluq.discord.lavaplayer.tools.DataFormatTools.durationTextToMillis(DataFormatTools.java:91)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.extractPolymerData(YoutubeSearchProvider.java:161)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.lambda$polymerExtractTracks$0(YoutubeSearchProvider.java:149)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider$$Lambda$216/0000000000000000.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.polymerExtractTracks(YoutubeSearchProvider.java:148)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.extractSearchResults(YoutubeSearchProvider.java:94)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71)
	... 20 common frames omitted
```

I analysed the problem using a Intellij debugger and it is likely caused by YouTube livestreams that don't have 'lengthText' in the json in the method YoutubeSearchProvider#extractPolymerData.

This json text was extracted using the debugger from the method:

```
{"videoId":"BD_guK9b64k","thumbnail":{"thumbnails":[{"url":"https://i.ytimg.com/vi/BD_guK9b64k/hqdefault_live.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLAj88J02oE2MUjRKyhS5H4XNJXq3Q","width":168,"height":94},{"url":"https://i.ytimg.com/vi/BD_guK9b64k/hqdefault_live.jpg?sqp=-oaymwEiCMQBEG5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLAb-JjV4gjq1fIVxEQ0vgA9efY-YQ","width":196,"height":110},{"url":"https://i.ytimg.com/vi/BD_guK9b64k/hqdefault_live.jpg?sqp=-oaymwEjCPYBEIoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAs43e72atxWby_uHDb4csYphvThQ","width":246,"height":138},{"url":"https://i.ytimg.com/vi/BD_guK9b64k/hqdefault_live.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBcp20yLb8nfafPqKpKRarRPwROzQ","width":336,"height":188}]},"title":{"runs":[{"text":"Spinnin' | 24/7 Live Radio | Deep House, Chill House | Dance Music to relax/study to"}],"accessibility":{"accessibilityData":{"label":"Spinnin' | 24/7 Live Radio | Deep House, Chill House | Dance Music to relax/study to von Spinnin' Records vor 2 Monaten 3.221.505 Aufrufe"}}},"descriptionSnippet":{"runs":[{"text":"Listen to our Deep House Hits playlists: ..."}]},"longBylineText":{"runs":[{"text":"Spinnin' Records","navigationEndpoint":{"clickTrackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE=","commandMetadata":{"webCommandMetadata":{"url":"/user/SpinninRec","webPageType":"WEB_PAGE_TYPE_BROWSE","rootVe":3611}},"browseEndpoint":{"browseId":"UCpDJl2EmP7Oh90Vylx0dZtA","canonicalBaseUrl":"/user/SpinninRec"}}}]},"viewCountText":{"runs":[{"text":"519"},{"text":" Zuschauer"}]},"navigationEndpoint":{"clickTrackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMAREyBnNlYXJjaFIFbXVzaWOaAQMQ9CQ=","commandMetadata":{"webCommandMetadata":{"url":"/watch?v=BD_guK9b64k","webPageType":"WEB_PAGE_TYPE_WATCH","rootVe":3832}},"watchEndpoint":{"videoId":"BD_guK9b64k"}},"badges":[{"metadataBadgeRenderer":{"style":"BADGE_STYLE_TYPE_LIVE_NOW","label":"Jetzt live","trackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE="}}],"ownerBadges":[{"metadataBadgeRenderer":{"icon":{"iconType":"CHECK_CIRCLE_THICK"},"style":"BADGE_STYLE_TYPE_VERIFIED","tooltip":"Bestätigt","trackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE="}}],"ownerText":{"runs":[{"text":"Spinnin' Records","navigationEndpoint":{"clickTrackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE=","commandMetadata":{"webCommandMetadata":{"url":"/user/SpinninRec","webPageType":"WEB_PAGE_TYPE_BROWSE","rootVe":3611}},"browseEndpoint":{"browseId":"UCpDJl2EmP7Oh90Vylx0dZtA","canonicalBaseUrl":"/user/SpinninRec"}}}]},"shortBylineText":{"runs":[{"text":"Spinnin' Records","navigationEndpoint":{"clickTrackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE=","commandMetadata":{"webCommandMetadata":{"url":"/user/SpinninRec","webPageType":"WEB_PAGE_TYPE_BROWSE","rootVe":3611}},"browseEndpoint":{"browseId":"UCpDJl2EmP7Oh90Vylx0dZtA","canonicalBaseUrl":"/user/SpinninRec"}}}]},"trackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARFAidfv-oqX-J8E","showActionMenu":false,"shortViewCountText":{"runs":[{"text":"519"},{"text":" aktive Zuschauer"}]},"menu":{"menuRenderer":{"items":[{"menuServiceItemRenderer":{"text":{"runs":[{"text":"In die Wiedergabeliste"}]},"icon":{"iconType":"ADD_TO_QUEUE_TAIL"},"serviceEndpoint":{"clickTrackingParams":"CI8BEP6YBBgFIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true}},"signalServiceEndpoint":{"signal":"CLIENT_SIGNAL","actions":[{"clickTrackingParams":"CI8BEP6YBBgFIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{}},"addToPlaylistCommand":{"openMiniplayer":true,"videoId":"BD_guK9b64k","listType":"PLAYLIST_EDIT_LIST_TYPE_QUEUE","onCreateListCommand":{"clickTrackingParams":"CI8BEP6YBBgFIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true,"apiUrl":"/youtubei/v1/playlist/create"}},"createPlaylistServiceEndpoint":{"videoIds":["BD_guK9b64k"],"params":"CAQ%3D"}},"videoIds":["BD_guK9b64k"]}}]}},"trackingParams":"CI8BEP6YBBgFIhMI-ty95NTK6gIVi458Ch1cDAER"}}],"trackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE=","accessibility":{"accessibilityData":{"label":"Aktionsmenü"}}}},"channelThumbnailSupportedRenderers":{"channelThumbnailWithLinkRenderer":{"thumbnail":{"thumbnails":[{"url":"https://yt3.ggpht.com/a-/AOh14Gg3OsF35UAiGIEiCR6ffj9c58X3-7I9QpXxTw=s68-c-k-c0x00ffffff-no-rj-mo","width":68,"height":68}]},"navigationEndpoint":{"clickTrackingParams":"CIwBENwwGAMiEwj63L3k1MrqAhWLjnwKHVwMARE=","commandMetadata":{"webCommandMetadata":{"url":"/user/SpinninRec","webPageType":"WEB_PAGE_TYPE_BROWSE","rootVe":3611}},"browseEndpoint":{"browseId":"UCpDJl2EmP7Oh90Vylx0dZtA","canonicalBaseUrl":"/user/SpinninRec"}},"accessibility":{"accessibilityData":{"label":"Zum Kanal"}}}},"thumbnailOverlays":[{"thumbnailOverlayToggleButtonRenderer":{"isToggled":false,"untoggledIcon":{"iconType":"WATCH_LATER"},"toggledIcon":{"iconType":"CHECK"},"untoggledTooltip":"Später ansehen","toggledTooltip":"Hinzugefügt","untoggledServiceEndpoint":{"clickTrackingParams":"CI4BEPnnAxgCIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true,"apiUrl":"/youtubei/v1/browse/edit_playlist"}},"playlistEditEndpoint":{"playlistId":"WL","actions":[{"addedVideoId":"BD_guK9b64k","action":"ACTION_ADD_VIDEO"}]}},"toggledServiceEndpoint":{"clickTrackingParams":"CI4BEPnnAxgCIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true,"apiUrl":"/youtubei/v1/browse/edit_playlist"}},"playlistEditEndpoint":{"playlistId":"WL","actions":[{"action":"ACTION_REMOVE_VIDEO_BY_VIDEO_ID","removedVideoId":"BD_guK9b64k"}]}},"untoggledAccessibility":{"accessibilityData":{"label":"Später ansehen"}},"toggledAccessibility":{"accessibilityData":{"label":"Hinzugefügt"}},"trackingParams":"CI4BEPnnAxgCIhMI-ty95NTK6gIVi458Ch1cDAER"}},{"thumbnailOverlayToggleButtonRenderer":{"untoggledIcon":{"iconType":"ADD_TO_QUEUE_TAIL"},"toggledIcon":{"iconType":"PLAYLIST_ADD_CHECK"},"untoggledTooltip":"In die Wiedergabeliste","toggledTooltip":"Hinzugefügt","untoggledServiceEndpoint":{"clickTrackingParams":"CI0BEMfsBBgDIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true}},"signalServiceEndpoint":{"signal":"CLIENT_SIGNAL","actions":[{"clickTrackingParams":"CI0BEMfsBBgDIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{}},"addToPlaylistCommand":{"openMiniplayer":true,"videoId":"BD_guK9b64k","listType":"PLAYLIST_EDIT_LIST_TYPE_QUEUE","onCreateListCommand":{"clickTrackingParams":"CI0BEMfsBBgDIhMI-ty95NTK6gIVi458Ch1cDAER","commandMetadata":{"webCommandMetadata":{"url":"/service_ajax","sendPost":true,"apiUrl":"/youtubei/v1/playlist/create"}},"createPlaylistServiceEndpoint":{"videoIds":["BD_guK9b64k"],"params":"CAQ%3D"}},"videoIds":["BD_guK9b64k"]}}]}},"untoggledAccessibility":{"accessibilityData":{"label":"In die Wiedergabeliste"}},"toggledAccessibility":{"accessibilityData":{"label":"Hinzugefügt"}},"trackingParams":"CI0BEMfsBBgDIhMI-ty95NTK6gIVi458Ch1cDAER"}},{"thumbnailOverlayNowPlayingRenderer":{"text":{"runs":[{"text":"Läuft gerade"}]}}}]}
```

**Comment by Gregyyy** [comment]
Found that this is a duplicate of #495
