### ISSUE TITLE
Video not available ? Not all the time.

### ISSUE THREAD

**Issue by ZzmaxzZ81** [sedmelluq/lavaplayer#505]
Hi,
I have a problem with lavaplayer : 
When I launch my program on my personal PC, everything works.
But when I launch it on a dedicated server, **some** video can't be played... **FriendlyException:** 
```
juil. 25 17:48:15 ns333337 bash[2923]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is not available.
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.checkStatusBlock(DefaultYoutubeTrackDetailsLoader.java:103)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:200)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:224)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:220)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:96)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
juil. 25 17:48:15 ns333337 bash[2923]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
juil. 25 17:48:15 ns333337 bash[2923]:         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
juil. 25 17:48:15 ns333337 bash[2923]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
juil. 25 17:48:15 ns333337 bash[2923]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
juil. 25 17:48:15 ns333337 bash[2923]:         at java.base/java.lang.Thread.run(Thread.java:834)
```

I don't know why the same video works on my personal computer not on the dedicated server.

**Comment by MCOfficer** [comment]
> This video is not available.

that sounds as if the server is in a different country, where the video is blocked for some reason.

**Comment by ZzmaxzZ81** [comment]
Same country :/

**Comment by sedmelluq** [comment]
This comes from YouTube reporting "Video unavailable", which only happens if it either geoblocks or if the video has been removed or never existed. No way to influence that from LP side.
