### ISSUE TITLE
IPv6 Extension not working

### ISSUE THREAD

**Issue by AggroMC** [sedmelluq/lavaplayer#512]
I use Lavaplayer for some time now but Youtube is permanentely blocking my IPs. So i decided to use the IPv6 Addon but now i have an error:
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to www.youtube.com:443 [www.youtube.com/2a00:....:4001:802:0:0:0:....] failed: connect timed out
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:162)
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:81)
        at com.sedmelluq.discord.lavaplayer.tools.http.SimpleHttpClientConnectionManager.connect(SimpleHttpClientConnectionManager.java:90)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:35)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26)
        ... 15 common frames omitted
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator$AdditionalDetails: Encountered when opening a connection with the following details:
  host: https://www.youtube.com:443
localAddress: /2a00:....:4001:802:0:0:0:...
  remoteAddress: www.youtube.com/2a00:....:4001:802:0:0:0:...:443
  connectTimeout: 3000
  triedAddresses: www.youtube.com/2a00:....:4001:802:0:0:0:...

How can i fix this error or increase the timeout?

**Comment by Portagoras** [comment]
I wonder how you implemented it, as my bot still gets into the ratelimit with the extension enabled...
