### ISSUE TITLE
I can't fix this error... "lava-daemon-pool-playback-4-thread-1"

### ISSUE THREAD

**Issue by Ludicrous245** [sedmelluq/lavaplayer#520]
```
Exception in thread "lava-daemon-pool-playback-4-thread-1" java.lang.UnsatisfiedLinkError: 'long com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(int, int)'
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(Native Method)
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

system is raspberrypi 4
it's aarch64
so I tried put libconnector.so in aarch64 folder and I also tried put libconnector.so in linux-arm 
but it dosen't work

what is problem

**Comment by aikaterna** [comment]
You need `com.sedmelluq:lavaplayer-natives-extra:1.3.13`.
See https://discordapp.com/channels/125227483518861312/263484072389640193/642792431783510017 in the JDA server for sed's message about it.

**Comment by Ludicrous245** [comment]
> You need `com.sedmelluq:lavaplayer-natives-extra:1.3.13`.
> See https://discordapp.com/channels/125227483518861312/263484072389640193/642792431783510017 in the JDA server for sed's message about it.

how can i import that?

**Comment by Ludicrous245** [comment]
> You need `com.sedmelluq:lavaplayer-natives-extra:1.3.13`.
> See https://discordapp.com/channels/125227483518861312/263484072389640193/642792431783510017 in the JDA server for sed's message about it.

I tried it, but it didn't work.

**Comment by sedmelluq** [comment]
Relevant: https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#8d9389a5

However, would like to see why the `com.sedmelluq:lavaplayer-natives-extra:1.3.13` does not work. Can you update to the latest LP, and try with that dependency, and show the full exception that it throws?
