### ISSUE TITLE
ConcurrentModificationException when trying to remove AudioEventAdaptor on track end

### ISSUE THREAD

**Issue by Trevor159** [sedmelluq/lavaplayer#547]
I think this is a valid use case although I am new to this library so feel free to tell me if I am wrong.
This code produces this stacktrace
```
@Override
public void onTrackEnd(AudioPlayer player, AudioTrack track, AudioTrackEndReason endReason)
{
	player.removeListener(this);
}
```
```
2020-11-01 15:10:16.960 ERROR 31896 --- [ Sending Thread] n.d.jda.internal.audio.AudioConnection   : There was an error while getting next audio packet

java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042) ~[na:na]
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:366) ~[lavaplayer-1.3.50.jar:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.handleTerminator(DefaultAudioPlayer.java:262) ~[lavaplayer-1.3.50.jar:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:241) ~[lavaplayer-1.3.50.jar:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:216) ~[lavaplayer-1.3.50.jar:na]
	at gg.trevor.hellodiscord.bot.audio.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:33) ~[classes/:na]
	at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:672) ~[JDA-4.2.0_209.jar:4.2.0_209]
	at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:662) ~[JDA-4.2.0_209.jar:4.2.0_209]
	at net.dv8tion.jda.api.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69) ~[JDA-4.2.0_209.jar:4.2.0_209]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

**Comment by sedmelluq** [comment]
Your PR proposed making a copy on each iteration, but I've instead made it copy on change, as that is a less common operation, thus makes less unnecessary copies. Released in `1.3.60`.
