### ISSUE TITLE
1.3.60 Age restricted tracks not working

### ISSUE THREAD

**Issue by aikaterna** [sedmelluq/lavaplayer#558]
I am a Lavalink user, but I am using Lavaplayer 1.3.60.

Playing an age-restricted track causes a traceback.

Some test tracks:
https://www.youtube.com/watch?v=dmJefsOErr0
https://www.youtube.com/watch?v=gAs9HZC9c7Y
https://www.youtube.com/watch?v=HcXNPI-IPPM
https://www.youtube.com/watch?v=zwT6DZCQi9k

```
2020-11-18 08:18:04.212  WARN 1764 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of gAs9HZC9c7Y

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:199) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:83) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:54) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.60.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
        ... 11 common frames omitted
```

**Comment by sedmelluq** [comment]
Fixed in 1.3.61.
