### ISSUE TITLE
Soundcloud Links fail, "Suspicious exception for loading item [URL] , This url does not appear to be a playable track."

### ISSUE THREAD

**Issue by Djinnistorm** [sedmelluq/lavaplayer#571]
Running https://github.com/jagrosh/MusicBot on a Windows 10 PC. Can confirm soundcloud links were functioning as of 3 days ago, and youtube links are still working. 

Example error in the java console: 
```
[19:39:30] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://soundcloud.com/user-694398002/excuse-my-rudeness-but-could-you-please-die
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:31)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
	
Let me know if there's more info I can provide to assist.

**Comment by reptar25** [comment]
This got fixed with #570 and update today. Update to 1.3.64 and try it again?

**Comment by Djinnistorm** [comment]
I see. I'm not the owner of the bot's git project but I've managed to manually update before, I'll give it a shot. Thanks

**Comment by Djinnistorm** [comment]
Ok after finally managing to set up Maven, I have updated the musicbot with the latest lavaplayer and it DOES resolve this. Closing, thanks again!
