### ISSUE TITLE
Problems with Lavaplayer on Raspberry Pi

### ISSUE THREAD

**Issue by MineKing9534** [sedmelluq/lavaplayer#576]
I have written a Discord bot using JDA and lavaplayer. It's working fine on several machines with different OSes - with one exception: on a Raspberry Pi running Pi OS and OpenJDK, starting the TrackScheduler immediately calls onTrackEnd() with the reason "LOAD_FAILED".

Maybe this is related to the JVM as on all machines using ORACLE JDK, there's no problem. On Pi OS, I have to use OpenJDK. Any idea how to debug this issue?

**Comment by MCOfficer** [comment]
there should be a stacktrace or at least more log messages that you can provide us with.

**Comment by MineKing9534** [comment]
where can i find these stacktraces or logs. im not getting exceptions or something like this. Thy only Thing that happens is that the bot leavs the voicechat instandly after joining it

**Comment by MCOfficer** [comment]
Configure whatever logging implementation you use to log on DEBUG level.

**Comment by MineKing9534** [comment]
I don't have one :( How can I get one?

**Comment by MCOfficer** [comment]
Choose one slf4j-copatible logging implementation and follow its instructions. I'd go with [logback](https://logback.qos.ch/), but it's personal preference.

**Comment by MineKing9534** [comment]
I have installed logback and configured it to debug level. When starting, the bot, I get lots of messages but still none for joining and leaving the channel

Verbindung zur Datenbank hergestellt
08:33:36.531 [main] DEBUG c.s.d.l.t.i.TrustManagerBuilder - Certificate list /certificates/extended.txt not present in classpath.
08:33:38.772 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [610dc6090e7e2b22-FRA]
08:33:39.981 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [610dc60fed732b22-FRA]
08:33:40.008 [main] INFO  n.d.j.a.JDA - Login Successful!
08:33:40.107 [main] DEBUG n.d.j.a.u.SessionControllerAdapter - Creating new worker handle for shard pool 0
08:33:40.109 [main] DEBUG n.d.j.a.u.SessionControllerAdapter - Running worker
08:33:40.111 [ConcurrentSessionController-Worker-0] DEBUG n.d.j.a.u.SessionControllerAdapter - Running connect node for shard Shard [0 / 1]
Bot online
08:33:40.701 [JDA MainWS-WriteThread] INFO  n.d.j.i.r.WebSocketClient - Connected to WebSocket
08:33:40.702 [JDA MainWS-WriteThread] DEBUG n.d.j.i.r.WebSocketClient - Connected with gateway intents: 111111111101111
08:33:40.702 [JDA MainWS-WriteThread] DEBUG n.d.j.i.r.WebSocketClient - Sending Identify-packet...
08:33:40.741 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Got HELLO packet (OP 10). Initializing keep-alive.
08:33:41.230 [JDA MainWS-ReadThread] DEBUG n.d.j.i.h.GuildSetupController - Setting incomplete count to 4
08:33:41.541 [JDA MainWS-ReadThread] DEBUG n.d.j.i.h.GuildSetupController - Finished setup for guild xxx firing cached events 0
08:33:41.716 [JDA MainWS-ReadThread] DEBUG n.d.j.i.h.GuildSetupController - Finished setup for guild xxx firing cached events 0
08:33:41.728 [JDA MainWS-ReadThread] DEBUG n.d.j.i.h.GuildSetupController - Finished setup for guild xxx firing cached events 0
08:33:41.746 [JDA MainWS-ReadThread] INFO  n.d.j.a.JDA - Finished Loading!
08:33:41.750 [JDA MainWS-ReadThread] DEBUG n.d.j.i.h.GuildSetupController - Finished setup for guild xxx firing cached events 0
08:33:42.511 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.RateLimiter - Caching bucket hash GET/channels/{channel_id}/messages/{message_id} -> xxx
08:33:42.513 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:42.761 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.RateLimiter - Caching bucket hash DELETE/guilds/{guild_id}/members/{user_id}/roles/{role_id} -> xxx
08:33:42.762 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:42.821 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:42.969 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.003 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.RateLimiter - Caching bucket hash PUT/guilds/{guild_id}/members/{user_id}/roles/{role_id} -> xxx
08:33:43.004 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.007 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.135 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.187 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.313 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.358 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.469 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.559 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.662 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.818 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:43.983 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:44.303 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:44.305 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.RateLimiter - Backing off 8585 ms for bucket xxx:xxx:channel_id:webhook_id
08:33:45.943 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.RateLimiter - Caching bucket hash PATCH/channels/{channel_id} -> xxx
08:33:45.944 [JDA RateLimit-Worker 3] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.079 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.262 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.421 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.612 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.772 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:53.930 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:54.088 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:54.257 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:54.438 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:54.614 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:33:54.615 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.RateLimiter - Backing off 8447 ms for bucket xxx:xxx:channel_id:webhook_id
08:34:03.233 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:03.440 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:03.597 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:03.802 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:04.011 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:04.170 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:04.399 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:04.601 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:04.831 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:05.004 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:05.006 [JDA RateLimit-Worker 4] DEBUG n.d.j.i.r.RateLimiter - Backing off 8232 ms for bucket xxx:xxx:channel_id:webhook_id
08:34:07.763 [JDA RateLimit-Worker 1] DEBUG n.d.j.i.r.RateLimiter - Removed 11 expired buckets
08:34:13.420 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:13.581 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:13.769 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:13.965 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:14.120 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:14.287 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:14.474 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:14.631 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:14.786 [JDA RateLimit-Worker 2] DEBUG n.d.j.i.r.Requester - Received response with following cf-rays: [xxx-FRA]
08:34:37.756 [JDA RateLimit-Worker 5] DEBUG n.d.j.i.r.RateLimiter - Removed 1 expired buckets
09:02:44.972 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Got Reconnect request (OP 7). Closing connection now...
09:02:45.180 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Got disconnected from WebSocket (Code: 4900). Attempting to resume session
09:02:45.181 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Attempting to reconnect in 0s
09:02:45.183 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Attempting to reconnect!
09:02:45.418 [JDA MainWS-WriteThread] DEBUG n.d.j.i.r.WebSocketClient - Connected to WebSocket
09:02:45.418 [JDA MainWS-WriteThread] DEBUG n.d.j.i.r.WebSocketClient - Sending Resume-packet...
09:02:45.424 [JDA MainWS-ReadThread] DEBUG n.d.j.i.r.WebSocketClient - Got HELLO packet (OP 10). Initializing keep-alive.
09:02:45.538 [JDA MainWS-ReadThread] DEBUG n.d.j.a.JDA - Successfully resumed Session!

**Comment by MineKing9534** [comment]
I was able to solve the problem by following the steps from https://stackoverflow.com/questions/61640438/jda-discord-bot-with-lavaplayer-not-working-properly-on-raspberry-pi-3b-raspbi

**Comment by MCOfficer** [comment]
Ah, so it was #16 after all. The log didn't look like it.

**Comment by MineKing9534** [comment]
After little changes on the bot it didnt work with libconnector.so. But I don't know what I've changed.
I have written a Bot with some less features and it worked fine with raspbian. but when i added more features and added the libconnector.so im getting this:


[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$239/0x6218b828@17c92e7
[lava-daemon-pool-playback-1-thread-1] INFO com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library connector: loading with filter null
[lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.lava.common.natives.NativeLibraryLoader - Native library connector: loading failed.
java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:136)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:152)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:128)
        ... 26 more
Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1611687481257
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.createDirectoriesWithFullPermissions(NativeLibraryLoader.java:207)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:148)
        ... 27 more
[lava-daemon-pool-playback-1-thread-1] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of tAGnKpE4NCI
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:294)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69)
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276)
        ... 10 more
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:136)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84)
        ... 24 more
Caused by: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:152)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:128)
        ... 26 more
Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1611687481257
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.createDirectoriesWithFullPermissions(NativeLibraryLoader.java:207)
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:148)
        ... 27 more

**Comment by MCOfficer** [comment]
>  Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1611687481257

sounds like a permission error.

**Comment by MineKing9534** [comment]
Thank you very much, that was the Problem. Now the old bot works too.

**Comment by MineKing9534** [comment]
With the new logger, it was quite easy to find the actual problem. To prevent this, lavaplayer shouldn't use the same path for its temporary files for all users. Currently, it's not possible that different users launch lavaplayer. Not even at different times as the dir is also not cleaned up. Please add the user name or something else to the path in order to make it unique.

**Comment by sedmelluq** [comment]
Closing as author said they got things to work.
