### ISSUE TITLE
FriendlyException: Something went wrong when decoding the track

### ISSUE THREAD

**Issue by cloudybyte** [sedmelluq/lavaplayer#578]
I was reactivating my music bot and updating to the newest version of lavaplayer and I am getting this error message repeatedly after some time playing. I am then restarting the bot and everything works fine again for a while until it starts again... It doesn't seem like a problem with my code, because I can play the same tracks just fine after the restart... 
That error never happened to me in the past...

````

11:33:29.173 [lava-daemon-pool-info-loader-5-thread-1] INFO : Track was loaded! Now playing: https://www.youtube.com/watch?v=uJvEV9C2sHQ Title: LEFT BOY feat. FERDINAND - SEX PARTY

11:33:29.727 [lava-daemon-pool-playback-4-thread-3] ERROR: Error in playback of uJvEV9C2sHQ

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.

	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)

	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293)

	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)

	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)

	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)

	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)

	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)

	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 

  lavaplayer.version: 1.3.67

  os.arch: amd64

  os.name: Linux

  os.version: 5.4.0-65-generic

  java.vendor: Oracle Corporation

  java.version: 11.0.10

  java.runtime.version: 11.0.10+9

  java.vm.version: 11.0.10+9

Caused by: java.lang.IllegalStateException: Cannot use the decoder after closing it.

	at com.sedmelluq.lava.common.natives.NativeResourceHolder.checkNotReleased(NativeResourceHolder.java:21)

	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusEncoder.encode(OpusEncoder.java:36)

	at com.sedmelluq.discord.lavaplayer.format.transcoder.OpusChunkEncoder.encode(OpusChunkEncoder.java:39)

	at com.sedmelluq.discord.lavaplayer.filter.BufferingPostProcessor.process(BufferingPostProcessor.java:34)

	at com.sedmelluq.discord.lavaplayer.filter.FinalPcmAudioFilter.dispatch(FinalPcmAudioFilter.java:157)

	at com.sedmelluq.discord.lavaplayer.filter.FinalPcmAudioFilter.process(FinalPcmAudioFilter.java:146)

	at com.sedmelluq.discord.lavaplayer.filter.equalizer.Equalizer.process(Equalizer.java:74)

	at com.sedmelluq.discord.lavaplayer.filter.converter.ToFloatAudioFilter.process(ToFloatAudioFilter.java:65)

	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.process(UserProvidedAudioFilters.java:76)

	at com.sedmelluq.discord.lavaplayer.filter.AudioPipeline.process(AudioPipeline.java:33)

	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.passDownstream(OpusPacketRouter.java:160)

	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:96)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)

	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)

	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)   
	... 10 more
```

**Comment by oleggtro** [comment]
any update on this?

**Comment by PatrSto** [comment]
I have the same problem too, any solutions?

**Comment by oleggtro** [comment]
lavaplayer seems a bit unmaintained rn

**Comment by Spimy** [comment]
Still nothing on this?

**Comment by oleggtro** [comment]
I don't think so

**Comment by Z0pyrus** [comment]
Still nothing?

**Comment by oleggtro** [comment]
any idea? @sedmelluq

**Comment by Its-Haze** [comment]
i have the same issue. ;/

**Comment by oleggtro** [comment]
lavaplayer seems dead tbh

**Comment by MCOfficer** [comment]
Use https://github.com/Walkyst/lavaplayer-fork

**Comment by Da-Real-Kryall** [comment]
I also have this issue, still nothing?

**Comment by MCOfficer** [comment]
Still the same solution, use Walkyst's fork and report any issues there.
