### ISSUE TITLE
InterruptedException

### ISSUE THREAD

**Issue by Endergame15** [sedmelluq/lavaplayer#58]
Hello Sedmelluq,
if a track is ending the player give us an InterruptedException. Discord make an update can you please update the player.

Full Exception:

at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
        at net.dv8tion.jda.core.requests.WebSocketClient.queueAudioDisconnect(WebSocketClient.java:1115)
        at net.dv8tion.jda.core.audio.AudioWebSocket.close(AudioWebSocket.java:450)
        at net.dv8tion.jda.core.audio.AudioConnection.close(AudioConnection.java:226)
        at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:139)
        at net.dv8tion.jda.core.managers.impl.AudioManagerImpl.closeAudioConnection(AudioManagerImpl.java:130)
        at audioManager.TrackManager.onTrackEnd(TrackManager.java:79)
        at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70)
        at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.dispatchEvent(AudioPlayer.java:295)
        at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.handleTerminator(AudioPlayer.java:217)
        at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provideDirectly(AudioPlayer.java:197)
        at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:167)
        at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18)
        at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.provide(AudioPlayer.java:162)
        at audioManager.PlayerSendHandler.canProvide(PlayerSendHandler.java:18)
        at net.dv8tion.jda.core.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:607)
        at net.dv8tion.jda.core.audio.factory.DefaultSendSystem.lambda$start$61(DefaultSendSystem.java:57)
        at java.lang.Thread.run(Thread.java:748)

Sorry for my bad english i am german.

~Endergame15

**Comment by napstr** [comment]
Hi, this is a JDA issue and actually working as intended. You need to adjust your code.
See for details: https://github.com/DV8FromTheWorld/JDA/issues/485
