### ISSUE TITLE
[WARN] [LocalAudioTrackExecutor]: Suspicious exception for playback of B01XQrlc_KI

### ISSUE THREAD

**Issue by SuperKali** [sedmelluq/lavaplayer#581]
Hi,

I've got this problem, some music through YouTube give me this error:

```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:200)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:88)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.67
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-13-amd64
  java.vendor: Oracle Corporation
  java.version: 1.8.0_252
  java.runtime.version: 1.8.0_252-b09
  java.vm.version: 25.252-b09
```

I don't know what is the problem, can you advise a better solution for fix it

Kind regards.

**Comment by sedmelluq** [comment]
Fixed in `1.3.69`.
