### ISSUE TITLE
NumberFormatException when using YouTubeAudioSourceManager#loadItem() with ytmsearch

### ISSUE THREAD

**Issue by Blad3Mak3r** [sedmelluq/lavaplayer#582]
When using ``YouTubeAudioSourceManager#loadItem()`` to search for songs from **YouTube Music**, it returns **NumberFormatException** with some tracks.

```
[03:36:59] [ lava-daemon-pool-playback-1-th ] SpotifyAudioSou  ERROR --> Exception searching YouTube track with 'ytmsearch:R.A.G.E., Bonka': java.lang.NumberFormatException: For input string: "Delusion"
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "Delusion"
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.loadSearchMusicResult(YoutubeSearchMusicProvider.java:77)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.searchMusic(YoutubeAudioSourceManager.java:274)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.searchMusic(YoutubeAudioSourceManager.java:228)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:37)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131)
	at net.hugebot.discord.music.sources.spotify.SpotifyAudioSourceManager.doYoutubeSearch(SpotifyAudioSourceManager.kt:88)
	at net.hugebot.discord.music.sources.spotify.SpotifyAudioSourceManager.doYoutubeSearchSingle$HugeBot(SpotifyAudioSourceManager.kt:96)
	at net.hugebot.discord.music.sources.spotify.SpotifyAudioSourceManager.doYoutubeSearchSingle$HugeBot$default(SpotifyAudioSourceManager.kt:94)
	at net.hugebot.discord.music.sources.spotify.SpotifyAudioTrack.retrieveYoutubeAudio(SpotifyAudioTrack.kt:32)
	at net.hugebot.discord.music.sources.spotify.SpotifyAudioTrack.process(SpotifyAudioTrack.kt:23)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NumberFormatException: For input string: "Delusion"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at com.sedmelluq.discord.lavaplayer.tools.DataFormatTools.durationTextToMillis(DataFormatTools.java:135)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.extractMusicData(YoutubeSearchMusicProvider.java:149)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.lambda$extractMusicTracks$0(YoutubeSearchMusicProvider.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.extractMusicTracks(YoutubeSearchMusicProvider.java:121)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.extractSearchResults(YoutubeSearchMusicProvider.java:86)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchMusicProvider.loadSearchMusicResult(YoutubeSearchMusicProvider.java:74)
	... 15 common frames omitted
```

This issue does not happen with the normal ``ytsearch`` or with ``AudioPlayerManager#loadItemOrdered()``

### System information
```
lavaplayer.version: 1.3.69
os.arch: amd64
os.name: Windows 10
os.version: 10.0
java.vendor: Amazon.com Inc.
java.version: 11.0.5
java.runtime.version: 11.0.5+10-LTS
java.vm.version: 11.0.5+10-LTS
```

### The way to reproduce it (Kotlin):
```kotlin
val audioItem = youtubeAsmInstance.loadItem(apmInstance, AudioReference("ytmsearch:R.A.G.E., Bonka", null))
```

#### So far I have found some queries with which this happens:
- ``ytmsearch:Dagga, Asonn``
- ``ytmsearch:Interstellar, Reggio``
- ``ytmsearch:R.A.G.E., Bonka``
- ``ytmsearch:Firefly, Dash Berlin`` (sometimes)

**Comment by sedmelluq** [comment]
Fixed in `1.3.71`.
