### ISSUE TITLE
mp4a codec is not supported

### ISSUE THREAD

**Issue by duncte123** [sedmelluq/lavaplayer#586]
When parsing videos from TikTok I ran into the issue that the codec was not usable.

Let me know if you need more info

VLC plays the file fine and gave me the following metadata about it
![image](https://user-images.githubusercontent.com/8843386/108540929-1c6ccd80-72e2-11eb-8af1-1df9ce04e043.png)

Exception:
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: The audio codec used in the track is not supported.
	at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.loadAudioTrack(MpegAudioTrack.java:65) ~[lavaplayer-1.3.71.jar:na]
	at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:41) ~[lavaplayer-1.3.71.jar:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.71.jar:na]
	at com.dunctebot.sourcemanagers.tiktok.TikTokAudioTrack.loadStream(TikTokAudioTrack.java:86) ~[skybot-source-managers-eece3fa.jar:na]
	at com.dunctebot.sourcemanagers.tiktok.TikTokAudioTrack.process(TikTokAudioTrack.java:69) ~[skybot-source-managers-eece3fa.jar:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.71.jar:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.71.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.71
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-65-generic
  java.vendor: AdoptOpenJDK
  java.version: 15.0.2
  java.runtime.version: 15.0.2+7
  java.vm.version: 15.0.2+7
```

The file dump created:
[DUMP.zip](https://github.com/sedmelluq/lavaplayer/files/6011860/DUMP.zip)

**Comment by muhimur9049** [comment]
Was going through logs yesterday and I saw the 8195 happen on my end for the first time. This is the link that causes it: `https://cdn.discordapp.com/attachments/692039523965861988/856151137483620402/WhatsApp_Video_2021-04-02_at_22.03.20_1.mp4`

I'm not sure if it's a downloaded TikTok video or not, but yeah

**Comment by DaliborTrampota** [comment]
https://cdn.discordapp.com/attachments/583996272898342912/857341893432180766/yoga_time.mp4
here is another one which gives the same error
