### ISSUE TITLE
JDA-NAS NoClassDefFoundError: com...tools/DaemonThreadFactory (and I read the FAQ...)

### ISSUE THREAD

**Issue by tycrek** [sedmelluq/lavaplayer#598]
<details>
<summary>Stacktrace</summary>

```
[JDA AudioConnection Guild: 819346319465644052 Ready Thread] ERROR AudioConnection - Uncaught exception in Audio ready-thread
java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager(NativeAudioSendFactory.java:38)
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance(NativeAudioSendFactory.java:69)
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start(NativeAudioSendSystem.java:23)
	at net.dv8tion.jda.internal.audio.AudioConnection.setupSendSystem(AudioConnection.java:301)
	at net.dv8tion.jda.internal.audio.AudioConnection.lambda$prepareReady$0(AudioConnection.java:232)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory
```

</details>

From the FAQ:

> ...version conflict resolution strategy in Maven

We don't use Maven anyway.

> An alternative is to use Gradle

Already using Gradle.

Currently our imports for Lavaplayer and JDA-NAS look like this:

```gradle
compile 'com.sedmelluq:lavaplayer:1.3.73'
compile files("lib/jda-nas-1.1.0.jar")
```

We're using `files` because at the time of building, JCenter was down (again!!) so JDA-NAS couldn't be downloaded and I had to manually add it (Lavaplayer was cached).

We add it to our bot as per the JDA-NAS readme:

```java
jda = JDABuilder.createLight(NeoConfig.Discord.token)
	.addEventListeners(commandClient, music)
	.enableIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_VOICE_STATES)
	.setAudioSendFactory(new NativeAudioSendFactory())
	.build();
```

Any ideas? This error occurred on both Windows 10 and Ubuntu 20.04 (program was running in a Docker container)

**Comment by tycrek** [comment]
Once JCenter eventually came back online I switched back to it and it worked fine....

**Comment by Z-EMB** [comment]
Not sure why you closed it. jcenter will disappear soon. jda-nas needs to be moved to the new repo.

**Comment by tycrek** [comment]
> 
> 
> Not sure why you closed it. jcenter will disappear soon. jda-nas needs to be moved to the new repo.

My issue is unrelated to JCenter being shut down and it's unrelated to Lavaplayer migrating to something else, that's why I closed it.
