### ISSUE TITLE
NoClassDefFound Exception DaemonThreadFactory

### ISSUE THREAD

**Issue by DSlyDog** [sedmelluq/lavaplayer#599]
Before this is dismissed as a repeat, it is not. This is not for the same issue as all the previous ones. I am not reporting that the class does not exist, because it does. I believe this to be a bug in the most recent version. When I compiled with 1.3.73 I got this error:

`java.lang.NoClassDefFoundError: com/sedmelluq/lava/common/tools/DaemonThreadFactory
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:105)
        at net.whispwriting.lotus.util.audio.LotusPlayer.<init>(LotusPlayer.java:21)
        at net.whispwriting.lotus.util.audio.LotusPlayer.getInstance(LotusPlayer.java:35)
        at net.whispwriting.lotus.command.commands.Play.onCommand(Play.java:32)
        at net.whispwriting.lotus.command.CommandHandler.onGuildMessageReceived(CommandHandler.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:410)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.lava.common.tools.DaemonThreadFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 27 more`

Now, switching to 1.3.72, it worked just fine. I'm using Maven. What I noticed was, the path listed in the error report does not match the path in the lavaplayer or lavaplayer-common libraries. I currently have 1.0.6 for the lavaplayer-common dependency. This appeared to be the latest version on bintray. Also, after browsing the previous issues created with this class, the path was not the same as the one I'm seeing here.

EDIT: After converting my project to gradle, it worked with 1.3.73. I don't know if the repositories the dependency managers draw from differs, so this is either a bug in the maven version, or it is just maven being dumb as explained in the FAQ.

**Comment by sedmelluq** [comment]
Yeah this is Maven being dumb, first entry in FAQ explains this: https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md
