### ISSUE TITLE
I was playing some songs , and at a time just stop working to play tracks

### ISSUE THREAD

**Issue by MegasusBMS** [sedmelluq/lavaplayer#606]
when I start a track, it stops instantly, and if it has something in the queue it gives play and how it starts it ends and so, all of a sudden, it went and then it didn't go, I tried to put version 1.3.74 but it doesn't find it, 1.3.73 happens the same way, and I use 1.3.72

**Comment by MegasusBMS** [comment]
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.player.AudioPlayerManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more

**Comment by MegasusBMS** [comment]
<dependency>
			<groupId>com.sedmelluq</groupId>
			<artifactId>lavaplayer</artifactId>
			<version>1.3.74</version>
		</dependency>
		<repository>
			<id>central</id>
			<name>bintray</name>
			<url>https://jcenter.bintray.com</url>
		</repository>
