### ISSUE TITLE
Bot joins the VoiceChannel and does not play anything due to an RuntimeException

### ISSUE THREAD

**Issue by Alexander-Schwarze** [sedmelluq/lavaplayer#612]
I wanted my Discord-Bot to play youtube-music in VoiceChannels. My implementation is almost the same as the demo-jda as I never used Lavaplayer before.
The bot joins the room, but does not play anything. So I followed the FAQ-tips. With that, I caugth a FriendlyException in AudioEventAdapter#onTrackException , which looks as followed:

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluqdiscord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.73
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 12.0.2
  java.runtime.version: 12.0.2+10
  java.vm.version: 12.0.2+10
Caused by: java.lang.RuntimeException: Error when extracting data EID: 86eeb58d-b2ce-42ab-a2dc-0e546a55c84c, mainJson<redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:66)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:41)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
        ... 4 more
Caused by: java.lang.RuntimeException: no PLAYER_JS_URL in youtube root EID: 6a8d6a18-895f-4015-825c-1be80f95418c, html<redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.augmentWithPlayerScript(DefaultYoutubeTrackDetailsLoader.java:251)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:61)
        ... 8 more
 

I didn't find anything about what the exception refers to. Am I missing something in my implementation?
The track I tried playing was the youtube-video: https://www.youtube.com/watch?v=dQw4w9WgXcQ

I think the issue is the same as this one (but not sure): #607

**Comment by MCOfficer** [comment]
duplicate of #597, update to 1.3.74 or newer.

**Comment by Alexander-Schwarze** [comment]
Okay thanks, didnt see this issue!
