### ISSUE TITLE
Error In Playback Of [X]

### ISSUE THREAD

**Issue by sgoudham** [sedmelluq/lavaplayer#624]
Recently started using this for my discord bot but randomly getting the following errors below on (seemingly) random songs: 

```
[lava-daemon-pool-playback-1-thread-2] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of PWgvGjAhvIw
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.75
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: AdoptOpenJDK
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9
  java.vm.version: 11.0.11+9
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 more
```
I can't figure out if this is on my end or on the library.

**Comment by MCOfficer** [comment]
My first idea is a new kinda age-restriction, or that they're DMCA'd. Can you post some of those song links? also, which country your bot runs in?

**Comment by sgoudham** [comment]
Ah right okay, that's quite odd because (in the above example) it was [this](https://www.youtube.com/watch?v=PWgvGjAhvIw) song and once I requested it again in the queue after restarting the bot, it proceeded to play without any issues. 

The bot should be running on a server within the UK and it's not age-restricted here.

**Comment by Shadorc** [comment]
It happens when there's a config mismatch so lavaplayer incorrectly deciphers the cipher
https://discord.com/channels/125227483518861312/263484072389640193/842601055862128670

**Comment by sgoudham** [comment]
> 
> 
> It happens when there's a config mismatch so lavaplayer incorrectly deciphers the cipher
> https://discord.com/channels/125227483518861312/263484072389640193/842601055862128670

What discord server is this?

**Comment by Shadorc** [comment]
It's official lavaplayer channel from JDA server
