### ISSUE TITLE
Error : Name may not be blank

### ISSUE THREAD

**Issue by mopmop682** [sedmelluq/lavaplayer#635]
Hey, guy i get this error when i run this 'https://f5-pa6-2.nrjaudio.fm/fr/30001/mp3_128.mp3?origine=mytuner&cdn_path=adswizz_lbs11&access_token=8f6db022859c4d5c847ad7165a89a65d'

`[09:45:18] [ERROR] [AudioPlayer]: Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackStartEvent@3e6bcf4d threw an exception.
java.lang.IllegalArgumentException: Name may not be blank
        at net.dv8tion.jda.internal.utils.Checks.notBlank(Checks.java:80)
        at net.dv8tion.jda.api.entities.Activity.listening(Activity.java:177)
        at fr.mael.starnetwork.starmusic.audio.NowplayingHandler.onTrackUpdate(NowplayingHandler.java:106)
        at fr.mael.starnetwork.starmusic.audio.AudioHandler.onTrackStart(AudioHandler.java:143)
        at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:72)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:360)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.startTrack(DefaultAudioPlayer.java:113)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.playTrack(DefaultAudioPlayer.java:76)
        at fr.mael.starnetwork.starmusic.audio.AudioHandler.lambda$playFromDefault$0(AudioHandler.java:107)
        at fr.mael.starnetwork.starmusic.playlist.PlaylistLoader$Playlist$1.trackLoaded(PlaylistLoader.java:138)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by MCOfficer** [comment]
This is not an LP error, this is originating from your code:

```
java.lang.IllegalArgumentException: Name may not be blank at net.dv8tion.jda.internal.utils.Checks.notBlank(Checks.java:80) at net.dv8tion.jda.api.entities.Activity.listening(Activity.java:177) at fr.mael.starnetwork.starmusic.audio.NowplayingHandler.onTrackUpdate(NowplayingHandler.java:106) at fr.mael.starnetwork.starmusic.audio.AudioHandler.onTrackStart(AudioHandler.java:143) at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:72) at
```

JDA is complaining that you give it an empty name as activity.
