### ISSUE TITLE
Problems with Soundcloud on 1.3.77 - Http Status 401

### ISSUE THREAD

**Issue by HagarJNode** [sedmelluq/lavaplayer#636]
I get an 401 when I try to play SoundCloud links:

21:54:21.623 ERROR c.s.d.l.t.p.LocalAudioTrackExecutor - Error in playback of O:https://api-v2.soundcloud.com/media/soundcloud:tracks:287610097/5cb0eb62-d774-4f56-860f-0832f62eb1a3/stream/hls
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.77
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 1.8.0_222
  java.runtime.version: 1.8.0_222-10
  java.vm.version: 25.222-b10
Caused by: java.io.IOException: Invalid status code for soundcloud stream: 401
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudHelper.loadPlaybackUrl(SoundCloudHelper.java:22)

**Comment by unwell35** [comment]
same

**Comment by MCOfficer** [comment]
If either of you could test #637 , that would be great.

**Comment by HagarJNode** [comment]
It works in 1.3.78 - thanks :)
