### ISSUE TITLE
Error while decoding the track | EOFException

### ISSUE THREAD

**Issue by VocalZero** [sedmelluq/lavaplayer#639]
On my Discord bot I use LavaPlayer for all the audio part. But I'm struggling with an annoying error where I don't currently have a place to look. At the beginning I had played an AAC stream that often had an error in some guilds and no longer played. I switched the stream from AAC to MP3 to test if it gets better. Unfortunately no success. I am now stuck at this error and do not get further.

Error: https://pastebin.com/XC2irW5r

**Comment by VocalZero** [comment]
Besides this error, there seems to be an error when loading the stream from time to time.

`
0|discordbot  | Jun 19, 2021 11:11:44 PM eu.atomicnetworks.discordbot.managers.BackendManager$2 loadFailed
0|discordbot  | SCHWERWIEGEND: null
0|discordbot  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
0|discordbot  |         at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34)
0|discordbot  |         at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81)
0|discordbot  |         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
0|discordbot  |         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
0|discordbot  |         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
0|discordbot  |         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
0|discordbot  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
0|discordbot  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
0|discordbot  |         at java.lang.Thread.run(Thread.java:748)
0|discordbot  |         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
0|discordbot  |   lavaplayer.version: 1.3.77
0|discordbot  |   os.arch: amd64
0|discordbot  |   os.name: Linux
0|discordbot  |   os.version: 4.19.0-16-amd64
0|discordbot  |   java.vendor: AdoptOpenJDK
0|discordbot  |   java.version: 1.8.0_282
0|discordbot  |   java.runtime.version: 1.8.0_282-b08
0|discordbot  |   java.vm.version: 25.282-b08

`
