### ISSUE TITLE
HTTP/S Stream not supportet

### ISSUE THREAD

**Issue by Zemux1613** [sedmelluq/lavaplayer#644]
I try the following code:

`
playerManager.loadItem("https://laut.fm/bravefm", new AudioLoadResultHandler() {

					public void trackLoaded(AudioTrack track) {

						player.playTrack(track);

					}

					public void playlistLoaded(AudioPlaylist playlist) {
						player.playTrack(playlist.getTracks().get(0));
					}

					public void noMatches() {	}

					public void loadFailed(FriendlyException exception) {
						exception.printStackTrace();
					}
				});
`

And I get following Stacktrace:

`com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34)
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

Why is the url not supportet? I dont understand!!!

**Comment by MCOfficer** [comment]
Because nobody has written  a handler for laut.fm yet (See [Supported Formats](https://github.com/sedmelluq/lavaplayer#supported-formats)). If you can get the URL to an actual media file, such as a .m3u, mp3 or similar, then LP can handle it, not matter what website it's from.

For your website, try this: https://bravefm.stream.laut.fm/bravefm

**Comment by Zemux1613** [comment]
Hey I tried also http://stream.laut.fm/bravefm.m3u and http://stream.laut.fm/bravefm.pls but it's the same issue.

The URL https://stream.laut.fm/bravefm at top was playable but after change jda version to an build version lavaplayer said exception... Im confused

**Comment by MCOfficer** [comment]
I tested it successfully on 1.3.55 (yeah, outdated as hell :/ ). What LP version does it work on, and which ones fail to play it?

**Comment by Zemux1613** [comment]
I use LP 1.3.77 and all of the urls at top failed by my code.

**Comment by Zemux1613** [comment]
I upgrade LP to 1.3.78 also same issue

**Comment by Zemux1613** [comment]
What the hell.... I downgrade to LP version 1.3.55 and LP play my stream... Whats that? An bug?

**Comment by MCOfficer** [comment]
Seems like it. can you provide the stacktrace you get using 1.3.78 and https://bravefm.stream.laut.fm/bravefm ?

**Comment by Zemux1613** [comment]
Both the same as top. Only in env output is LP version another
