### ISSUE TITLE
Soundcloud doesn't work again!

### ISSUE THREAD

**Issue by Asherlam** [sedmelluq/lavaplayer#653]
```
2021-08-27 20:34:30.822 ERROR 33 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.78.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-73-generic
  java.vendor: Oracle Corporation
  java.version: 16.0.2
  java.runtime.version: 16.0.2+7-67
  java.vm.version: 16.0.2+7-67
Caused by: java.lang.RuntimeException: No track JSON found EID: d40cb96a-d7a3-4daf-9ac2-1f27ac6804f7, html <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.78.jar!/:na]
        ... 11 common frames omitted
```

SoundCloud link: https://soundcloud.com/aire9803/aire-colorfc-lilium-x7

**Comment by phamleduy04** [comment]
I have same issue 

```
[19:33:31] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://soundcloud.com/thu-hi-n-809236619/sets/nha
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudPlaylistLoader.loadFromSet(DefaultSoundCloudPlaylistLoader.java:73)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudPlaylistLoader.load(DefaultSoundCloudPlaylistLoader.java:61)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:119)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-81-generic
  java.vendor: Ubuntu
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
  java.vm.version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
Caused by: java.lang.RuntimeException: No track JSON found EID: 2e36330a-b37b-4a44-a66b-9ac409928e21, html <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        ... 13 common frames omitted

```

Soundcloud link: https://soundcloud.com/thu-hi-n-809236619/sets/nha

**Comment by WearifulCupid0** [comment]
#650

**Comment by FreshSupaSulley** [comment]
Same issue as #650, the solution there works. For now, use NavyCake's commit. Switch your lavaplayer library to his in Maven like this:


<repositories>
	<repository>
		<id>jitpack.io</id>
		<url>https://jitpack.io</url>
	</repository>
</repositories>


<dependencies>
	<dependency>
		<groupId>com.github.NavyCake</groupId>
		<artifactId>lavaplayer</artifactId>
		<version>soundcloud-SNAPSHOT</version>
	</dependency>
</dependencies>

**Comment by phamleduy04** [comment]
I got 401 Unauthorized when trying to download it 😢

**Comment by FreshSupaSulley** [comment]
> I got 401 Unauthorized when trying to download it 😢

I deleted my old reply. Turns out it's now a private repository (?). Best I can do for you is give you the external JAR for you to manually add to your build: https://drive.google.com/file/d/1PkCQyD_7i78pGQ5oqOPgkj9hLDRXXLH6/view?usp=sharing

**Comment by HagarJNode** [comment]
Having the same issue
