### ISSUE TITLE
Unable to play soundcloud tracks (v1.3.78)

### ISSUE THREAD

**Issue by BilliAlpha** [sedmelluq/lavaplayer#656]
The changelog for version 1.3.78 says it fixes loading of soundcloud tracks however it seems that it still doesn't work.

The issue seems similar to #636 (fixed in #637)

```
com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Suspicious exception for loading item https://soundcloud.com/monodie/monodie-toma-la-mano
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$758/0x00000000d8042310.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-13-amd64
  java.vendor: AdoptOpenJDK
  java.version: 1.8.0_292
  java.runtime.version: 1.8.0_292-b10
  java.vm.version: openj9-0.26.0
Caused by: java.lang.RuntimeException: No track JSON found EID: 1e170567-8812-49d4-adb6-de60d9a180b0, html <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        ... 12 common frames omitted
```

**Comment by MCOfficer** [comment]
dupes #653
