### ISSUE TITLE
"Something went wrong when looking up the track"

### ISSUE THREAD

**Issue by NuggetRP** [sedmelluq/lavaplayer#657]
Well, i followed the guide without any luck, then i followed the demo and i got the bot to work, but now im getting this message:
"Something went wrong when looking up the track"
Stack trace:
`com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.77
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 14.0.2
  java.runtime.version: 14.0.2+12-46
  java.vm.version: 14.0.2+12-46
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionSocketFactory(ExtendedHttpClientBuilder.java:91)
	at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionManager(ExtendedHttpClientBuilder.java:84)
	at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.build(ExtendedHttpClientBuilder.java:54)
	at com.sedmelluq.discord.lavaplayer.tools.io.AbstractHttpInterfaceManager.getSharedClient(AbstractHttpInterfaceManager.java:83)
	at com.sedmelluq.discord.lavaplayer.tools.io.ThreadLocalHttpInterfaceManager.getInterface(ThreadLocalHttpInterfaceManager.java:34)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.getHttpInterface(SoundCloudAudioSourceManager.java:161)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:201)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	... 6 more
`

**Comment by NuggetRP** [comment]
Fixed: Changed from Java 14 to Java 13 ;)
