### ISSUE TITLE
No supported audio format in the MP4 file.

### ISSUE THREAD

**Issue by itsmishra19** [sedmelluq/lavaplayer#663]
Tried to play videos from Reddit and got this error

Java Version: Java 11

Video Link: "https://v.redd.it/ooiy0ctgpol71/DASH_1080.mp4?source=fallback"

Stack Trace:
```java
2021-09-16 08:26:00.180 ERROR 2175 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: No supported audio format in the MP4 file.
    at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:36) ~[lavaplayer-fork-3a54cbd43b.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-fork-3a54cbd43b.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-3a54cbd43b.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-3a54cbd43b.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-3a54cbd43b.jar!/:na]
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.94-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.11.0-1018-gcp
  java.vendor: Ubuntu
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9-Ubuntu-0ubuntu2.18.04
  java.vm.version: 11.0.11+9-Ubuntu-0ubuntu2.18.04
```

**Comment by duncte123** [comment]
The video doesn't have an audio stream, lavaplayer needs an audio stream to play back
