### ISSUE TITLE
Youtube works fine, spotify does not?

### ISSUE THREAD

**Issue by nullpat** [sedmelluq/lavaplayer#666]
This is appearing like an issue that was on an earlier version of lavaplayer but 1.3.78 should be fine?

```
</html>

[04:30:34] [WARN] [DefaultAudioPlayerManager]: Suspicious exception for loading item https://soundcloud.com/vincentmix/coachella
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 4.14.243-185.433.amzn2.x86_64
  java.vendor: Amazon.com Inc.
  java.version: 11.0.12
  java.runtime.version: 11.0.12+7-LTS
  java.vm.version: 11.0.12+7-LTS
Caused by: java.lang.RuntimeException: No track JSON found EID: 1c6fa821-1d5a-4595-833b-0cbc0f491632, html <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	... 13 common frames omitted
[03:39:19] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:channel_id=708165175341088828 Retry-After: 145000 ms
[03:52:44] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:channel_id=708165175341088828 Retry-After: 73000 ms
[04:05:17] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:channel_id=708165175341088828 Retry-After: 93000 ms
[04:10:39] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:channel_id=708165175341088828 Retry-After: 519000 ms
[04:26:58] [WARN] [ExceptionTools]: No track JSON found EID: de93bcd9-b4e7-416f-808b-48804452bf67, html: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="theme-color" content="#333">
<link rel="dns-prefetch" href="//style.sndcdn.com">
```

**Comment by MCOfficer** [comment]
dupes #651 #653, fixed by #650
