### ISSUE TITLE
Error "at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<clinit>"

### ISSUE THREAD

**Issue by fernandopal** [sedmelluq/lavaplayer#67]
`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<clinit>(DefaultAudioPlayerManager.java:75)
	at com.minebone.bonecord.commands.Music.<clinit>(Music.java:30)
	at com.minebone.bonecord.core.Main.main(Main.java:43)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more`

Line 30 of the class Music: http://prntscr.com/h2eiug
Line 43 of the class Main: http://prntscr.com/h2ejf4

**Comment by sedmelluq** [comment]
No response to given diagnosis, closing.
