### ISSUE TITLE
m3u and m3u8 playlists are improperly handled

### ISSUE THREAD

**Issue by forkiesassds** [sedmelluq/lavaplayer#678]
Playlist files like m3u and m3u8 are improperly handled, as only one of the songs in the playlist play, and doesn't handle each of the entries as a single song

**Comment by cwchristerw** [comment]
I can play this file in VLC media player and ffmpeg...
https://digitacdn.akamaized.net/hls/live/629243/loop/master-128000.m3u8

**Comment by cwchristerw** [comment]
It gives error in logs of https://github.com/freyacodes/Lavalink
```
2022-02-13 23:53:04.872  INFO 1 --- [  XNIO-1 task-5] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://digitacdn.akamaized.net/hls/live/629243/loop/master-128000.m3u8"
2022-02-13 23:53:04.959 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: The playlist file contains no links.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:36) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-99-generic
  java.vendor: Oracle Corporation
  java.version: 16.0.2
  java.runtime.version: 16.0.2+7-67
  java.vm.version: 16.0.2+7-67

2022-02-13 23:53:04.960 ERROR 1 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: The playlist file contains no links.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:36) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-1.3.96.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-99-generic
  java.vendor: Oracle Corporation
  java.version: 16.0.2
  java.runtime.version: 16.0.2+7-67
  java.vm.version: 16.0.2+7-67
```
