### ISSUE TITLE
Suddently stopped working

### ISSUE THREAD

**Issue by martinpro1000** [sedmelluq/lavaplayer#691]
For me Lavaplayer suddently stopped working. When I try to play a song, it doesn't get played, but the bot prints it's name. When I paste link, the fail method is called.

What do you think is the problem?

**Comment by MCOfficer** [comment]
No telling without any error or stacktrace (check your debug logs), but most likely #688  given the timing.

**Comment by martinpro1000** [comment]
So that is the stack trace I get from the load Failed method:

```com.sedmelluq.discord.lavaplayer.tools.FriendlyException:__ Loading information for a YouTube track failed.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:220)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:232)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:228)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:99)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:64)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:42)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.77
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Eclipse Adoptium
  java.version: 17.0.2
  java.runtime.version: 17.0.2+8
  java.vm.version: 17.0.2+8
Caused by: java.lang.RuntimeException: Error when extracting data EID: ab7dae61-f3ed-4261-a38c-eafcc1416f76, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:70)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:208)
	... 16 more
Caused by: java.lang.RuntimeException: Neither player nor playerResponse in result EID: 711f11ee-8348-4083-bf0c-5fac320bbafa, json <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackJsonData.fromMainResult(YoutubeTrackJsonData.java:53)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:80)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59)
	... 18 more```

**Comment by martinpro1000** [comment]
Can confirm that others also get that exception.

**Comment by MCOfficer** [comment]
Duplicate of #688, then.

**Comment by martinpro1000** [comment]
Is problem in our code or not?

**Comment by MCOfficer** [comment]
No, in lavaplayer. That issue also has a fix linked. You might want to use [Walkyst's fork](https://github.com/Walkyst/lavaplayer-fork) instead of this repo instead, it's kinda dead atm.

**Comment by martinpro1000** [comment]
Thanks for response.

So the fix is to use the forked version. I don't know why Lavaplayer stopped working suddently, but I will try to use the forked version and tell you if that's the fix for me.

**Comment by martinpro1000** [comment]
For me the bot just started working again today, maybe youtube fixed something?

**Comment by julianoBRL** [comment]
i'm having the same problem

**Comment by MCOfficer** [comment]
Same solution: this repo is dead, use a fork. these days it's https://github.com/lavalink-devs/lavaplayer
