### ISSUE TITLE
Bot is not playing Music

### ISSUE THREAD

**Issue by TheRazvy** [sedmelluq/lavaplayer#700]
`2022-08-15 11:37:15.204  INFO 43650 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "635878806506307603", "track": "QAAAjAIALUFSQVNIIGZlYXQuIFNOT09QIERPR0cgLSBPTUcgKE9mZmljaWFsIHZpZGVvKQAFQXJhc2gAAAAAAAMRKAALcFh2b2VDZ2k1OW8AAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1wWHZvZUNnaTU5bwAHeW91dHViZQAAAAAAAAAA", "noReplace": false, "startTime": "0", "pause": false}
2022-08-15 11:37:16.161 ERROR 43650 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of pXvoeCgi59o

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98-devoxin
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-54-generic
  java.vendor: Ubuntu
  java.version: 11.0.16
  java.runtime.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
  java.vm.version: 11.0.16+8-post-Ubuntu-0ubuntu120.04
Caused by: java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:645) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:243) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:160) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:197) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:46) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:34) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[walkyst-lavaplayer-85f4877.jar!/:na]
	... 4 common frames omitted

2022-08-15 11:37:16.440  INFO 43650 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "635878806506307603"}
`

**Comment by MCOfficer** [comment]
> lavaplayer.version: 1.3.98-devoxin

Check back with lavalink, that fork of LP doesn't live here and has been archived for a while.

**Comment by SphynxHF** [comment]
You are using Walkyst you should get in touch with him on his fork https://github.com/walkyst/lavaplayer-fork
