### ISSUE TITLE
Failed to play twitch

### ISSUE THREAD

**Issue by ChocoMeow** [sedmelluq/lavaplayer#707]
```
2022-12-23 03:37:31.919  INFO 72 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.twitch.tv/iitztimmy"
2022-12-23 03:37:34.554  INFO 72 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track last stream ever... until i come back from christmas break / Follow my socials @iiTzTimmy
2022-12-23 03:37:35.109  INFO 72 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "781828787352240129", "track": "QAAAwwIAWWxhc3Qgc3RyZWFtIGV2ZXIuLi4gdW50aWwgaSBjb21lIGJhY2sgZnJvbSBjaHJpc3RtYXMgYnJlYWsgLyBGb2xsb3cgbXkgc29jaWFscyBAaWlUelRpbW15AAlpaXR6dGltbXl//////////wAfaHR0cHM6Ly93d3cudHdpdGNoLnR2L2lpdHp0aW1teQEBAB9odHRwczovL3d3dy50d2l0Y2gudHYvaWl0enRpbW15AAZ0d2l0Y2gAAAAAAAAAAA==", "startTime": "0", "noReplace": false}
2022-12-23 03:37:35.124  INFO 72 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$801/0x00000008012ac400@76f561a3
2022-12-23 03:37:35.126  INFO 72 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2022-12-23 03:37:35.204  INFO 72 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: successfully loaded.
2022-12-23 03:37:35.487  WARN 72 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of https://www.twitch.tv/iitztimmy

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Failed to get next part of the stream.
    at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentUrl(M3uStreamSegmentUrlProvider.java:79) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentStream(M3uStreamSegmentUrlProvider.java:92) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamAudioTrack.lambda$process$0(M3uStreamAudioTrack.java:33) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.loadNextStream(ChainedInputStream.java:25) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.read(ChainedInputStream.java:55) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.tools.io.GreedyInputStream.read(GreedyInputStream.java:23) ~[lavaplayer-1.3.99.1.jar!/:na]
    at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106) ~[na:na]
    at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.processPacket(MpegTsElementaryInputStream.java:132) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.findElementaryData(MpegTsElementaryInputStream.java:113) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.read(MpegTsElementaryInputStream.java:87) ~[lavaplayer-1.3.99.1.jar!/:na]
    at java.base/java.io.FilterInputStream.read(FilterInputStream.java:82) ~[na:na]
    at com.sedmelluq.discord.lavaplayer.container.mpegts.PesPacketInputStream.makeBytesAvailable(PesPacketInputStream.java:38) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.mpegts.PesPacketInputStream.read(PesPacketInputStream.java:74) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.scanForPacketHeader(AdtsStreamReader.java:76) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.findPacketHeader(AdtsStreamReader.java:59) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.findPacketHeader(AdtsStreamReader.java:46) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.provideFrames(AdtsStreamProvider.java:62) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.container.adts.AdtsAudioTrack.process(AdtsAudioTrack.java:35) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.stream.MpegTsM3uStreamAudioTrack.processJoinedStream(MpegTsM3uStreamAudioTrack.java:25) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamAudioTrack.process(M3uStreamAudioTrack.java:34) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.twitch.TwitchStreamAudioTrack.process(TwitchStreamAudioTrack.java:56) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:354) ~[lavaplayer-1.3.99.1.jar!/:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.99.1-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-1025-gcp
  java.vendor: N/A
  java.version: 17.0.3
  java.runtime.version: 17.0.3+7-nixos
  java.vm.version: 17.0.3+7-nixos
Caused by: java.io.IOException: Unexpected response code from access token request: 410
    at com.sedmelluq.discord.lavaplayer.source.twitch.TwitchStreamSegmentUrlProvider.loadAccessToken(TwitchStreamSegmentUrlProvider.java:85) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.twitch.TwitchStreamSegmentUrlProvider.fetchSegmentPlaylistUrl(TwitchStreamSegmentUrlProvider.java:54) ~[lavaplayer-1.3.99.1.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentUrl(M3uStreamSegmentUrlProvider.java:53) ~[lavaplayer-1.3.99.1.jar!/:na]
    ... 28 common frames omitted
    ```

**Comment by MCOfficer** [comment]
>   lavaplayer.version: 1.3.99.1-original

That's not lavaplayer from this repo, this one only goes to 1.3.77. Are you looking for https://github.com/Walkyst/lavaplayer-fork ?

**Comment by ChocoMeow** [comment]
oh, sorry about that.
