### ISSUE TITLE
Problem with DefaultAudioPlayerManager

### ISSUE THREAD

**Issue by SpookyBuster** [sedmelluq/lavaplayer#72]
Hello, i was trying to make a music bot for discord, but i keep getting errors, about classes not being defined. This is the error:

[14:58:56] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[14:58:56] [Fatal] [JDA]: Encountered an exception:
[14:58:56] [Fatal] [JDA]: java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:92)
	at music.MusicPlayer.<init>(MusicPlayer.java:21)
	at music.PlayCommand.execute(PlayCommand.java:11)
	at leetbott.CommandHandler.runCommand(CommandHandler.java:155)
	at leetbott.CommandHandler.isVoiceCommand(CommandHandler.java:93)
	at leetbott.CommandHandler.permissionCheck(CommandHandler.java:101)
	at leetbott.CommandHandler.decideToRun(CommandHandler.java:55)
	at leetbott.CommandHandler.TheHandler(CommandHandler.java:37)
	at leetbott.EventStuff.onGuildMessageReceived(EventStuff.java:17)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:354)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:96)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:811)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:516)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.tools.DaemonThreadFactory

**Comment by SpookyBuster** [comment]
Now that error gone but now i have this one:

SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[15:37:31] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[15:37:31] [Fatal] [JDA]: Encountered an exception:
[15:37:31] [Fatal] [JDA]: java.lang.NoSuchMethodError: com.sedmelluq.discord.lavaplayer.tools.ExecutorTools.createEagerlyScalingExecutor(IIJLjava/lang/String;)Ljava/util/concurrent/ExecutorService;
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:94)
	at music.MusicPlayer.<init>(MusicPlayer.java:21)
	at music.PlayCommand.execute(PlayCommand.java:11)
	at leetbott.CommandHandler.runCommand(CommandHandler.java:155)
	at leetbott.CommandHandler.isVoiceCommand(CommandHandler.java:93)
	at leetbott.CommandHandler.permissionCheck(CommandHandler.java:101)
	at leetbott.CommandHandler.decideToRun(CommandHandler.java:55)
	at leetbott.CommandHandler.TheHandler(CommandHandler.java:37)
	at leetbott.EventStuff.onGuildMessageReceived(EventStuff.java:17)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:354)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:96)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:811)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:516)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by Devoxin** [comment]
Usually an issue with out-of-date dependencies or how you integrate dependencies. Do you use Gradle or Maven?

**Comment by SpookyBuster** [comment]
I use gradle, is that an issue?

**Comment by Devoxin** [comment]
Shouldn't be, are you using lavaplayer 1.2.44?

**Comment by SpookyBuster** [comment]
Ehm, im using lavaplayer 1.2.42, do you think that could be the issue?

**Comment by Devoxin** [comment]
Try update lavaplayer to 1.2.44 and update all your dependencies too.

**Comment by SpookyBuster** [comment]
Alright, will try to figure out how to do that, because im not very good at that stuff yet xd

**Comment by SpookyBuster** [comment]
Well i have solved that problem now, but now it keeps failing to load my tracks, and it says the severity of friendlyexception is FAULT. What does this mean?

**Comment by Devoxin** [comment]
Which source are you trying to load? YouTube? Also what's the full error?

**Comment by SpookyBuster** [comment]
Well im trying to load from youtube, and now i solved the FAULT, which is nice i suppose but it now gives a COMMON one, and it says the video was unavailable, and it says this for every video.

**Comment by SpookyBuster** [comment]
Sorry for the late response btw

**Comment by sedmelluq** [comment]
Give examples that don't work, and include the exception stack trace.

**Comment by sedmelluq** [comment]
No additional details provided within several months, closing.
