### ISSUE TITLE
lavaplayer joins audio channel but errors and doesnt play only on Macos Ventura

### ISSUE THREAD

**Issue by numbers1thru9** [sedmelluq/lavaplayer#720]
I am currently running on lavaplayer 1.3.77 with JDA 4.4.1_353 and just loaded my code onto a fresh machine setup running Macos Ventura on M2 CPU. The bot logs in and joins the audio channel on slash command just fine and stays connected. However no audio loads and plays and I get the following error on the CLI:

```[lava-daemon-pool-info-loader-2-thread-1] ERROR RestAction - RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction (or slash command) once!
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackActionImpl.tryAck(InteractionCallbackActionImpl.java:96)
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackActionImpl.queue(InteractionCallbackActionImpl.java:103)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
	at wasabi.commands.music.SlashPlay$ResultHandler.loadFailed(SlashPlay.java:59)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:239)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
[JDA MainWS-ReadThread] INFO RateLimiter - Waiting for 1 bucket(s) to finish. Average queue size of 0 requests
```

However if I run this exact same code on my Windows 11 machine or my Debian server that hosts my bot, everything works perfectly. I have the same Java version and JDKs. I even downloaded the known working jar from my server where its running now and I get the same error. Not sure if this is a lavaplayer version issue or something else.

**Comment by MCOfficer** [comment]
not sure about this error in particular, but please consider using the fork, you won't find any support or updates here.

https://github.com/Walkyst/lavaplayer-fork

**Comment by numbers1thru9** [comment]
> not sure about this error in particular, but please consider using the fork, you won't find any support or updates here.
> 
> https://github.com/Walkyst/lavaplayer-fork

Thank you @MCOfficer I honestly hadnt realized that this repo hasnt been updated in 2 years. I did as you suggested and changed my library over to the fork and launched it and that resolved my issues. Thanks a ton for that!
