### ISSUE TITLE
Bot just stopped playing tracks

### ISSUE THREAD

**Issue by martinpro1000** [sedmelluq/lavaplayer#723]
The bot suddently does not play any tracks. I found that the AudioPlayer#startTrack returns **false**. This is applies for original version of lavaplayer and the lavaplayer fork 1.4.2. What does it even mean if it returns false? In javadocs nothing is mentioned.

```
if(!this.player.startTrack(audioTrack, true)) {
            this.queue.offer(audioTrack);
            System.out.println("started the track");
        } else {
            System.out.println("could not play the track!");
   }
```

track friendly exception:

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
HIDDEN
Caused by: java.lang.RuntimeException: Error when extracting data EID: 2c1d3631-81ce-4dab-8b02-cf2255454e3f, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:70)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 4 more
Caused by: java.lang.RuntimeException: no PLAYER_JS_URL in youtube root EID: 765ee348-b860-491a-9320-e505d5a553a0, html <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.augmentWithPlayerScript(DefaultYoutubeTrackDetailsLoader.java:290)
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:65)
	... 8 more

**Comment by moritzmuescher** [comment]
is there a solution to this? i get the same error with the newest release
