### ISSUE TITLE
Error when trying to play anything from NicoNico since they when back up.

### ISSUE THREAD

**Issue by Simnico99** [sedmelluq/lavaplayer#732]
Lavaplayer throw the following error when trying to play any tracks/video from NicoNico 

I am using Lavalink and Lavalink4Net

```
2024-08-07T21:20:29.468Z ERROR 1 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of sm24120116

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.IllegalStateException: Invalid response received from NicoNico when loading video details
	at com.sedmelluq.discord.lavaplayer.source.nico.NicoAudioTrack.processJSON(NicoAudioTrack.java:142) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.nico.NicoAudioTrack.loadPlaybackUrl(NicoAudioTrack.java:113) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.nico.NicoAudioTrack.process(NicoAudioTrack.java:57) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.1.jar!/:na]
	... 4 common frames omitted
```

**Comment by Simnico99** [comment]
Wrong repos
