### ISSUE TITLE
YouTube certificate error

### ISSUE THREAD

**Issue by Gregyyy** [sedmelluq/lavaplayer#82]
When I try to play a YouTube video I get this exception:

`ERROR c.s.d.l.p.DefaultAudioPlayerManager - Error in loading item https://www.youtube.com/watch?v=8iNczzhZmbc
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:209)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrack(YoutubeAudioSourceManager.java:246)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:177)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:121)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: No trusted certificate found
        at sun.security.ssl.Alerts.getSSLException(java.base@9-internal/Alerts.java:198)
        at sun.security.ssl.SSLSocketImpl.fatal(java.base@9-internal/SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(java.base@9-internal/Handshaker.java:309)
        at sun.security.ssl.Handshaker.fatalSE(java.base@9-internal/Handshaker.java:303)
        at sun.security.ssl.ClientHandshaker.checkServerCerts(java.base@9-internal/ClientHandshaker.java:1841)
        at sun.security.ssl.ClientHandshaker.serverCertificate(java.base@9-internal/ClientHandshaker.java:1650)
        at sun.security.ssl.ClientHandshaker.processMessage(java.base@9-internal/ClientHandshaker.java:260)
        at sun.security.ssl.Handshaker.processLoop(java.base@9-internal/Handshaker.java:1003)
        at sun.security.ssl.Handshaker.processRecord(java.base@9-internal/Handshaker.java:937)
        at sun.security.ssl.SSLSocketImpl.processInputRecord(java.base@9-internal/SSLSocketImpl.java:1119)
        at sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:1056)
        at sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:955)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(java.base@9-internal/SSLSocketImpl.java:1382)
        at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1409)
        at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1393)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:60)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:264)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:193)
        ... 12 common frames omitted
Caused by: sun.security.validator.ValidatorException: No trusted certificate found
        at sun.security.validator.SimpleValidator.buildTrustedChain(java.base@9-internal/SimpleValidator.java:395)
        at sun.security.validator.SimpleValidator.engineValidate(java.base@9-internal/SimpleValidator.java:134)
        at sun.security.validator.Validator.validate(java.base@9-internal/Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(java.base@9-internal/X509TrustManagerImpl.java:343)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(java.base@9-internal/X509TrustManagerImpl.java:237)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(java.base@9-internal/X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.checkServerCerts(java.base@9-internal/ClientHandshaker.java:1820)
        ... 36 common frames omitted
`

**Comment by Gregyyy** [comment]
Issue fixed. Can be closed.

**Comment by thedarthonian** [comment]
I'm getting a similar issue, did you find the cause?
