### ISSUE TITLE
Uncaught exception in Audio ready-thread

### ISSUE THREAD

**Issue by Zeryther** [sedmelluq/lavaplayer#86]
Recently this error started showing up whenever I try to play a YouTube video

`22974 [JDA [0 / 10] AudioConnection Guild: 389140727243735053 Ready Thread] ERROR net.dv8tion.jda.core.audio.AudioConnection - Uncaught exception in Audio ready-thread
java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna581230142563279148.tmp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/jna-3506402/jna581230142563279148.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at tomp2p.opuswrapper.Opus.<clinit>(Opus.java:29)
        at net.dv8tion.jda.core.audio.AudioConnection.setupSendSystem(AudioConnection.java:266)
        at net.dv8tion.jda.core.audio.AudioConnection.lambda$ready$0(AudioConnection.java:130)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by sedmelluq** [comment]
This is from JDA, not lavaplayer.

**Comment by Zeryther** [comment]
Oops, okay I see.
I've been using debian wheezy and was able to find a workaround for this until I'm ready to update my production server.
