### ISSUE TITLE
Can't play .aac stream

### ISSUE THREAD

**Issue by ChristianKern97** [sedmelluq/lavaplayer#91]
I setup a small music bot with lava player and it works pretty good but it is not able to play .aac streams. I dont know if thats an issue of my program or the lava player. The problem only exists for aac URLs and it seems like it's a problem of the decoder. Here is the error i get:

`15:34:52.066 [lava-daemon-pool-playback-1-thread-2] ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of http://rs4.stream24.net/galaxy-passau.aac
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsAudioTrack.process(AdtsAudioTrack.java:36)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:51)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:83)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Error from decoder 8204
	at com.sedmelluq.discord.lavaplayer.natives.aac.AacDecoder.decode(AacDecoder.java:174)
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.decodeAndSend(AdtsStreamProvider.java:78)
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.provideFrames(AdtsStreamProvider.java:66)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:234)
	... 8 common frames omitted`

I hope this can be fixed somehow.

**Comment by sedmelluq** [comment]
Can you give example URLs this happens with? Also, currently AACP (most streams <48kbps) are not supported, but I would like to check if this is the case currently.

**Comment by ChristianKern97** [comment]
http://rs4.stream24.net/galaxy-passau.aac is an example. For me it's not to important because i can use other streams but in general this is pretty anoying.
By the way do you know why some youtube videos won't play while others will? It has nothing to do with copyright i think. They get the track and its information but throw a NullPointException.

**Comment by ChristianKern97** [comment]
http://rs4.stream24.net/galaxy-passau.aac is an example. For me it's not to important because i can use other streams but in general this is pretty anoying.

**Comment by sedmelluq** [comment]
This is indeed because there is currently no support for SBR or PS (collectively referred to as AAC+). This will be fixed soon.

**Comment by ChristianKern97** [comment]
Ok thanks alot for your answer.

**Comment by sedmelluq** [comment]
Fixed as of `1.2.50`.

**Comment by ChristianKern97** [comment]
Thanks. Great work 👍
