### ISSUE TITLE
This video is unavailable

### ISSUE THREAD

**Issue by Jisaneko** [sedmelluq/lavaplayer#92]
Every time I try to play a song or a video from Youtube I get this exception thrown:
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable.
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReasonFromStatus(YoutubeAudioSourceManager.java:318)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:309)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:292)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:207)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrack(YoutubeAudioSourceManager.java:260)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:191)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:130)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:438)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:228)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
Songs and audio from other platforms seem to work (I have only checked SoundCloud and that one seems to work just fine) but nothing from YouTube is working for me. 
I'm aware that the exception is thrown when the video is unavailable in my country but I get this for EVERY Youtube video, ones I know aren't unavailable.

**Comment by shikhir-arora** [comment]
Are you running the latest LavaPlayer version?

**Comment by Jisaneko** [comment]
I am using 1.2.49. (Maven)

**Comment by sedmelluq** [comment]
Make sure you are not converting the input to lowercase before you pass it to lavaplayer. I have seen this being the cause several times in the past.

**Comment by Jisaneko** [comment]
OH I see. Thanks for the help that was exactly the problem. (Quite a silly one at that too)
