### ISSUE TITLE
Error: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by cocomine** [sedmelluq/lavaplayer#95]
The following error occurred after I entered the URL

```
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 141146 [lava-daemon-pool-info-loader-2-thread-1] ERROR com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Error in loading item https://soundcloud.com/phantomsage/phantom-sage-spirit-feat-static-panic-1

[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:247)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:236)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: Caused by: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools$CustomHttpClientBuilder.createConnectionSocketFactory(HttpClientTools.java:179)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools$CustomHttpClientBuilder.createConnectionManager(HttpClientTools.java:167)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools$CustomHttpClientBuilder.build(HttpClientTools.java:160)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.io.AbstractHttpInterfaceManager.getSharedClient(AbstractHttpInterfaceManager.java:84)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.tools.io.ThreadLocalHttpInterfaceManager.getInterface(ThreadLocalHttpInterfaceManager.java:30)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.getHttpInterface(SoundCloudAudioSourceManager.java:172)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:285)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:263)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:121)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:438)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:228)
[21:39:02] [lava-daemon-pool-info-loader-2-thread-1/WARN]: 	... 6 more
```

**Comment by sedmelluq** [comment]
This is so commonly reported that I added it to FAQ: https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md

**Comment by cocomine** [comment]
The weird thing is
Testing on my computer is normal
But on [MCProHosting](https://mcprohosting.com/) above the problem

**Comment by cocomine** [comment]
Dependency tree:
```
[INFO] com.cocopixelmc:PlayerDeath2:jar:0.0.21
[INFO] +- com.sedmelluq:lavaplayer:jar:1.2.53:compile
[INFO] |  +- com.sedmelluq:lavaplayer-common:jar:1.0.6:runtime
[INFO] |  +- com.sedmelluq:lavaplayer-natives:jar:1.2.50:runtime
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:runtime
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:runtime
[INFO] |  +- commons-io:commons-io:jar:2.6:runtime
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.4:runtime
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:runtime
[INFO] |  +- org.jsoup:jsoup:jar:1.11.2:runtime
[INFO] |  \- net.iharder:base64:jar:2.3.9:runtime
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.4:compile
[INFO] +- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.25:compile
[INFO] +- net.dv8tion:JDA:jar:3.5.1_339:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.1:compile
[INFO] |  +- org.json:json:jar:20160810:compile
[INFO] |  +- net.sf.trove4j:trove4j:jar:3.0.3:compile
[INFO] |  +- net.java.dev.jna:jna:jar:4.4.0:compile
[INFO] |  \- com.neovisionaries:nv-websocket-client:jar:2.2:compile
[INFO] +- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] +- com.squareup.okhttp3:okhttp:jar:3.9.1:compile
[INFO] \- javax.mail:mail:jar:1.4.7:compile
[INFO]    \- javax.activation:activation:jar:1.1:compile
```

**Comment by cocomine** [comment]
I found the problem
